/**
 * Nutrition Database MCP Tool
 *
 * Provides access to food nutrition data
 */

import { Food, NutritionInfo } from '../types/index.js';

// Food nutrition database (simplified version of Chinese Food Composition Table)
const FOOD_DATABASE: Map<string, Food> = new Map();

initializeFoodDatabase();

function initializeFoodDatabase() {
  const foods: Food[] = [
    // ==================== 谷类 Grains ====================
    {
      id: 'nutrition-rice',
      name: '大米',
      category: '谷类',
      subcategory: '主食',
      nutrition: {
        calories: 130,
        protein: 2.6,
        carbohydrates: 28,
        fat: 0.3,
        fiber: 0.3,
        sugar: 0,
        sodium: 1,
        saturatedFat: 0.1,
        cholesterol: 0,
        vitamins: { vitaminA: 0, vitaminC: 0, vitaminD: 0, vitaminE: 0, vitaminK: 0, vitaminB12: 0, folate: 3 },
        minerals: { calcium: 10, iron: 0.2, magnesium: 10, potassium: 35, zinc: 0.5 },
      },
      unit: '100g',
      servingSize: 150,
      caloriesPer100g: 130,
      isAllergen: false,
      tags: ['主食', '碳水化合物', '能量', '米饭'],
    },
    {
      id: 'nutrition-brown-rice',
      name: '糙米',
      category: '谷类',
      subcategory: '杂粮',
      nutrition: {
        calories: 367,
        protein: 8,
        carbohydrates: 77,
        fat: 3,
        fiber: 3.5,
        sugar: 0,
        sodium: 5,
        saturatedFat: 0.5,
        cholesterol: 0,
        vitamins: { vitaminA: 0, vitaminC: 0, vitaminD: 0, vitaminE: 0.5, vitaminK: 1, vitaminB12: 0, folate: 20 },
        minerals: { calcium: 10, iron: 1.6, magnesium: 110, potassium: 250, zinc: 2 },
      },
      unit: '100g',
      servingSize: 150,
      caloriesPer100g: 367,
      isAllergen: false,
      tags: ['杂粮', '高纤维', '低GI', '全谷物'],
    },
    {
      id: 'nutrition-oats',
      name: '燕麦',
      category: '谷类',
      subcategory: '杂粮',
      nutrition: {
        calories: 389,
        protein: 17,
        carbohydrates: 66,
        fat: 7,
        fiber: 10,
        sugar: 0,
        sodium: 2,
        saturatedFat: 1,
        cholesterol: 0,
        vitamins: { vitaminA: 0, vitaminC: 0, vitaminD: 0, vitaminE: 1, vitaminK: 2, vitaminB12: 0, folate: 25 },
        minerals: { calcium: 54, iron: 5, magnesium: 138, potassium: 362, zinc: 4 },
      },
      unit: '100g',
      servingSize: 40,
      caloriesPer100g: 389,
      isAllergen: false,
      tags: ['杂粮', '高纤维', '高蛋白', '早餐', '心脏健康'],
    },
    {
      id: 'nutrition-wheat-flour',
      name: '面粉',
      category: '谷类',
      subcategory: '主食',
      nutrition: {
        calories: 364,
        protein: 10,
        carbohydrates: 76,
        fat: 1,
        fiber: 3,
        sugar: 0,
        sodium: 2,
        saturatedFat: 0.2,
        cholesterol: 0,
        vitamins: { vitaminA: 0, vitaminC: 0, vitaminD: 0, vitaminE: 0.3, vitaminK: 0.5, vitaminB12: 0, folate: 26 },
        minerals: { calcium: 15, iron: 1.2, magnesium: 22, potassium: 107, zinc: 1 },
      },
      unit: '100g',
      servingSize: 100,
      caloriesPer100g: 364,
      isAllergen: true,
      allergenType: ['gluten'],
      tags: ['主食', '烘焙', '面粉', '麸质'],
    },
    {
      id: 'nutrition-quinoa',
      name: '藜麦',
      category: '谷类',
      subcategory: '杂粮',
      nutrition: {
        calories: 368,
        protein: 14,
        carbohydrates: 64,
        fat: 6,
        fiber: 7,
        sugar: 0,
        sodium: 7,
        saturatedFat: 0.7,
        cholesterol: 0,
        vitamins: { vitaminA: 0, vitaminC: 0, vitaminD: 0, vitaminE: 1.2, vitaminK: 0, vitaminB12: 0, folate: 42 },
        minerals: { calcium: 17, iron: 1.5, magnesium: 64, potassium: 318, zinc: 1 },
      },
      unit: '100g',
      servingSize: 100,
      caloriesPer100g: 368,
      isAllergen: false,
      tags: ['超级食物', '完全蛋白', '无麸质', '高纤维'],
    },
    {
      id: 'nutrition-buckwheat',
      name: '荞麦',
      category: '谷类',
      subcategory: '杂粮',
      nutrition: {
        calories: 343,
        protein: 13,
        carbohydrates: 72,
        fat: 3,
        fiber: 10,
        sugar: 0,
        sodium: 4,
        saturatedFat: 0.5,
        cholesterol: 0,
        vitamins: { vitaminA: 0, vitaminC: 0, vitaminD: 0, vitaminE: 1, vitaminK: 7, vitaminB12: 0, folate: 30 },
        minerals: { calcium: 18, iron: 2.2, magnesium: 154, potassium: 320, zinc: 2.4 },
      },
      unit: '100g',
      servingSize: 100,
      caloriesPer100g: 343,
      isAllergen: true,
      allergenType: ['gluten'],
      tags: ['杂粮', '无麸质', '高纤维', '稳定血糖'],
    },
    {
      id: 'nutrition-sweet-potato',
      name: '红薯',
      category: '谷类',
      subcategory: '薯类',
      nutrition: {
        calories: 86,
        protein: 1.6,
        carbohydrates: 20,
        fat: 0.1,
        fiber: 3,
        sugar: 4,
        sodium: 55,
        saturatedFat: 0,
        cholesterol: 0,
        vitamins: { vitaminA: 14187, vitaminC: 2.4, vitaminD: 0, vitaminE: 0.3, vitaminK: 2, vitaminB12: 0, folate: 6 },
        minerals: { calcium: 30, iron: 0.6, magnesium: 25, potassium: 337, zinc: 0.3 },
      },
      unit: '100g',
      servingSize: 200,
      caloriesPer100g: 86,
      isAllergen: false,
      tags: ['薯类', '高维生素A', '高纤维', '低脂肪', '低GI'],
    },
    {
      id: 'nutrition-potato',
      name: '土豆',
      category: '谷类',
      subcategory: '薯类',
      nutrition: {
        calories: 77,
        protein: 2,
        carbohydrates: 17,
        fat: 0.1,
        fiber: 2,
        sugar: 0.8,
        sodium: 6,
        saturatedFat: 0,
        cholesterol: 0,
        vitamins: { vitaminA: 2, vitaminC: 20, vitaminD: 0, vitaminE: 0.1, vitaminK: 2, vitaminB12: 0, folate: 15 },
        minerals: { calcium: 12, iron: 0.8, magnesium: 23, potassium: 421, zinc: 0.3 },
      },
      unit: '100g',
      servingSize: 200,
      caloriesPer100g: 77,
      isAllergen: false,
      tags: ['薯类', '高钾', '维生素C', '能量'],
    },
    {
      id: 'nutrition-corn',
      name: '玉米',
      category: '谷类',
      subcategory: '杂粮',
      nutrition: {
        calories: 96,
        protein: 3.4,
        carbohydrates: 21,
        fat: 1.5,
        fiber: 2.7,
        sugar: 4.5,
        sodium: 1,
        saturatedFat: 0.2,
        cholesterol: 0,
        vitamins: { vitaminA: 9, vitaminC: 6, vitaminD: 0, vitaminE: 0.5, vitaminK: 0, vitaminB12: 0, folate: 26 },
        minerals: { calcium: 1, iron: 0.5, magnesium: 37, potassium: 248, zinc: 0.5 },
      },
      unit: '100g',
      servingSize: 200,
      caloriesPer100g: 96,
      isAllergen: false,
      tags: ['杂粮', '膳食纤维', '叶黄素', '抗氧化'],
    },
    // ==================== 蔬菜 Vegetables ====================
    {
      id: 'nutrition-broccoli',
      name: '西兰花',
      category: '蔬菜',
      subcategory: '十字花科',
      nutrition: {
        calories: 34,
        protein: 3,
        carbohydrates: 7,
        fat: 0.4,
        fiber: 3,
        sugar: 1,
        sodium: 33,
        saturatedFat: 0.1,
        cholesterol: 0,
        vitamins: { vitaminA: 623, vitaminC: 89, vitaminD: 0, vitaminE: 0.8, vitaminK: 102, vitaminB12: 0, folate: 63 },
        minerals: { calcium: 47, iron: 0.7, magnesium: 21, potassium: 316, zinc: 0.6 },
      },
      unit: '100g',
      servingSize: 200,
      caloriesPer100g: 34,
      isAllergen: false,
      tags: ['蔬菜', '高纤维', '维生素C', '抗癌', '十字花科', '高钙'],
    },
    {
      id: 'nutrition-spinach',
      name: '菠菜',
      category: '蔬菜',
      subcategory: '绿叶菜',
      nutrition: {
        calories: 23,
        protein: 3,
        carbohydrates: 4,
        fat: 0.4,
        fiber: 2,
        sugar: 0,
        sodium: 79,
        saturatedFat: 0.1,
        cholesterol: 0,
        vitamins: { vitaminA: 937, vitaminC: 28, vitaminD: 0, vitaminE: 2, vitaminK: 483, vitaminB12: 0, folate: 194 },
        minerals: { calcium: 99, iron: 2.7, magnesium: 79, potassium: 558, zinc: 0.5 },
      },
      unit: '100g',
      servingSize: 150,
      caloriesPer100g: 23,
      isAllergen: false,
      tags: ['绿叶菜', '铁', '维生素A', '维生素K', '叶酸', '超级食物'],
    },
    {
      id: 'nutrition-celery',
      name: '芹菜',
      category: '蔬菜',
      subcategory: '绿叶菜',
      nutrition: {
        calories: 16,
        protein: 1,
        carbohydrates: 3,
        fat: 0.2,
        fiber: 2,
        sugar: 1,
        sodium: 80,
        saturatedFat: 0,
        cholesterol: 0,
        vitamins: { vitaminA: 22, vitaminC: 4, vitaminD: 0, vitaminE: 0.3, vitaminK: 12, vitaminB12: 0, folate: 24 },
        minerals: { calcium: 40, iron: 0.3, magnesium: 11, potassium: 320, zinc: 0.1 },
      },
      unit: '100g',
      servingSize: 100,
      caloriesPer100g: 16,
      isAllergen: false,
      tags: ['绿叶菜', '降血压', '低热量', '纤维', '利尿'],
    },
    {
      id: 'nutrition-tomato',
      name: '番茄',
      category: '蔬菜',
      subcategory: '茄果类',
      nutrition: {
        calories: 18,
        protein: 1,
        carbohydrates: 4,
        fat: 0.2,
        fiber: 1,
        sugar: 3,
        sodium: 5,
        saturatedFat: 0,
        cholesterol: 0,
        vitamins: { vitaminA: 42, vitaminC: 14, vitaminD: 0, vitaminE: 0.5, vitaminK: 4, vitaminB12: 0, folate: 18 },
        minerals: { calcium: 10, iron: 0.3, magnesium: 9, potassium: 237, zinc: 0.2 },
      },
      unit: '100g',
      servingSize: 150,
      caloriesPer100g: 18,
      isAllergen: false,
      tags: ['蔬菜', '番茄红素', '抗氧化', '低热量', '美容'],
    },
    {
      id: 'nutrition-cucumber',
      name: '黄瓜',
      category: '蔬菜',
      subcategory: '瓜类',
      nutrition: {
        calories: 15,
        protein: 0.7,
        carbohydrates: 4,
        fat: 0.1,
        fiber: 0.5,
        sugar: 2,
        sodium: 2,
        saturatedFat: 0,
        cholesterol: 0,
        vitamins: { vitaminA: 5, vitaminC: 3, vitaminD: 0, vitaminE: 0, vitaminK: 16, vitaminB12: 0, folate: 7 },
        minerals: { calcium: 16, iron: 0.3, magnesium: 13, potassium: 147, zinc: 0.2 },
      },
      unit: '100g',
      servingSize: 200,
      caloriesPer100g: 15,
      isAllergen: false,
      tags: ['瓜类', '补水', '低热量', '清热', '美容'],
    },
    {
      id: 'nutrition-carrot',
      name: '胡萝卜',
      category: '蔬菜',
      subcategory: '根茎类',
      nutrition: {
        calories: 41,
        protein: 0.9,
        carbohydrates: 10,
        fat: 0.2,
        fiber: 3,
        sugar: 5,
        sodium: 69,
        saturatedFat: 0,
        cholesterol: 0,
        vitamins: { vitaminA: 16706, vitaminC: 6, vitaminD: 0, vitaminE: 0.7, vitaminK: 13, vitaminB12: 0, folate: 24 },
        minerals: { calcium: 33, iron: 0.3, magnesium: 12, potassium: 320, zinc: 0.2 },
      },
      unit: '100g',
      servingSize: 150,
      caloriesPer100g: 41,
      isAllergen: false,
      tags: ['根茎类', '高维生素A', '高纤维', '护眼', '胡萝卜素'],
    },
    {
      id: 'nutrition-bok-choy',
      name: '白菜',
      category: '蔬菜',
      subcategory: '十字花科',
      nutrition: {
        calories: 13,
        protein: 1.5,
        carbohydrates: 2,
        fat: 0.1,
        fiber: 1,
        sugar: 1,
        sodium: 50,
        saturatedFat: 0,
        cholesterol: 0,
        vitamins: { vitaminA: 8, vitaminC: 28, vitaminD: 0, vitaminE: 0, vitaminK: 33, vitaminB12: 0, folate: 43 },
        minerals: { calcium: 40, iron: 0.3, magnesium: 11, potassium: 178, zinc: 0.2 },
      },
      unit: '100g',
      servingSize: 200,
      caloriesPer100g: 13,
      isAllergen: false,
      tags: ['十字花科', '低热量', '维生素C', '清热', '家常菜'],
    },
    {
      id: 'nutrition-eggplant',
      name: '茄子',
      category: '蔬菜',
      subcategory: '茄果类',
      nutrition: {
        calories: 25,
        protein: 1,
        carbohydrates: 6,
        fat: 0.2,
        fiber: 3,
        sugar: 2,
        sodium: 2,
        saturatedFat: 0,
        cholesterol: 0,
        vitamins: { vitaminA: 8, vitaminC: 3, vitaminD: 0, vitaminE: 0.3, vitaminK: 3, vitaminB12: 0, folate: 22 },
        minerals: { calcium: 11, iron: 0.2, magnesium: 14, potassium: 229, zinc: 0.2 },
      },
      unit: '100g',
      servingSize: 200,
      caloriesPer100g: 25,
      isAllergen: false,
      tags: ['茄果类', '高纤维', '低热量', '花青素'],
    },
    {
      id: 'nutrition-green-pepper',
      name: '青椒',
      category: '蔬菜',
      subcategory: '茄果类',
      nutrition: {
        calories: 20,
        protein: 1,
        carbohydrates: 5,
        fat: 0.2,
        fiber: 2,
        sugar: 2,
        sodium: 4,
        saturatedFat: 0,
        cholesterol: 0,
        vitamins: { vitaminA: 18, vitaminC: 80, vitaminD: 0, vitaminE: 0.7, vitaminK: 5, vitaminB12: 0, folate: 19 },
        minerals: { calcium: 10, iron: 0.3, magnesium: 12, potassium: 211, zinc: 0.2 },
      },
      unit: '100g',
      servingSize: 100,
      caloriesPer100g: 20,
      isAllergen: false,
      tags: ['茄果类', '高维生素C', '高纤维', '开胃'],
    },
    {
      id: 'nutrition-lettuce',
      name: '生菜',
      category: '蔬菜',
      subcategory: '绿叶菜',
      nutrition: {
        calories: 15,
        protein: 1.4,
        carbohydrates: 3,
        fat: 0.2,
        fiber: 1,
        sugar: 1,
        sodium: 28,
        saturatedFat: 0,
        cholesterol: 0,
        vitamins: { vitaminA: 148, vitaminC: 15, vitaminD: 0, vitaminE: 0.2, vitaminK: 102, vitaminB12: 0, folate: 73 },
        minerals: { calcium: 33, iron: 0.5, magnesium: 14, potassium: 194, zinc: 0.2 },
      },
      unit: '100g',
      servingSize: 100,
      caloriesPer100g: 15,
      isAllergen: false,
      tags: ['绿叶菜', '低热量', '高水分', '减肥', '维生素K'],
    },
    {
      id: 'nutrition-asparagus',
      name: '芦笋',
      category: '蔬菜',
      subcategory: '茎类',
      nutrition: {
        calories: 20,
        protein: 2.2,
        carbohydrates: 4,
        fat: 0.1,
        fiber: 2,
        sugar: 2,
        sodium: 2,
        saturatedFat: 0,
        cholesterol: 0,
        vitamins: { vitaminA: 38, vitaminC: 5, vitaminD: 0, vitaminE: 1, vitaminK: 42, vitaminB12: 0, folate: 52 },
        minerals: { calcium: 24, iron: 2.1, magnesium: 14, potassium: 202, zinc: 0.5 },
      },
      unit: '100g',
      servingSize: 150,
      caloriesPer100g: 20,
      isAllergen: false,
      tags: ['茎类', '高蛋白', '高叶酸', '抗氧化', '利尿'],
    },
    {
      id: 'nutrition-mushroom',
      name: '蘑菇',
      category: '蔬菜',
      subcategory: '菌菇类',
      nutrition: {
        calories: 22,
        protein: 3,
        carbohydrates: 4,
        fat: 0.3,
        fiber: 2,
        sugar: 2,
        sodium: 5,
        saturatedFat: 0,
        cholesterol: 0,
        vitamins: { vitaminA: 0, vitaminC: 2, vitaminD: 0, vitaminE: 0.1, vitaminK: 0, vitaminB12: 0.1, folate: 17 },
        minerals: { calcium: 3, iron: 0.5, magnesium: 9, potassium: 318, zinc: 0.5 },
      },
      unit: '100g',
      servingSize: 100,
      caloriesPer100g: 22,
      isAllergen: false,
      tags: ['菌菇类', '低热量', '高蛋白', '维生素D', '免疫增强'],
    },
    {
      id: 'nutrition-kale',
      name: '羽衣甘蓝',
      category: '蔬菜',
      subcategory: '十字花科',
      nutrition: {
        calories: 49,
        protein: 4.3,
        carbohydrates: 9,
        fat: 0.9,
        fiber: 3.6,
        sugar: 2,
        sodium: 38,
        saturatedFat: 0.1,
        cholesterol: 0,
        vitamins: { vitaminA: 9990, vitaminC: 120, vitaminD: 0, vitaminE: 1.5, vitaminK: 817, vitaminB12: 0, folate: 141 },
        minerals: { calcium: 150, iron: 1.5, magnesium: 47, potassium: 491, zinc: 0.6 },
      },
      unit: '100g',
      servingSize: 100,
      caloriesPer100g: 49,
      isAllergen: false,
      tags: ['十字花科', '超级食物', '高维生素K', '高维生素A', '高钙'],
    },
    {
      id: 'nutrition-ginger',
      name: '生姜',
      category: '蔬菜',
      subcategory: '根茎类',
      nutrition: {
        calories: 80,
        protein: 2,
        carbohydrates: 18,
        fat: 0.8,
        fiber: 2,
        sugar: 1,
        sodium: 13,
        saturatedFat: 0.2,
        cholesterol: 0,
        vitamins: { vitaminA: 0, vitaminC: 5, vitaminD: 0, vitaminE: 0.3, vitaminK: 0, vitaminB12: 0, folate: 24 },
        minerals: { calcium: 33, iron: 0.6, magnesium: 44, potassium: 415, zinc: 0.3 },
      },
      unit: '100g',
      servingSize: 20,
      caloriesPer100g: 80,
      isAllergen: false,
      tags: ['根茎类', '驱寒', '抗炎', '助消化', '姜辣素'],
    },
    {
      id: 'nutrition-garlic',
      name: '大蒜',
      category: '蔬菜',
      subcategory: '鳞茎类',
      nutrition: {
        calories: 149,
        protein: 6.4,
        carbohydrates: 33,
        fat: 0.5,
        fiber: 2,
        sugar: 1,
        sodium: 17,
        saturatedFat: 0.1,
        cholesterol: 0,
        vitamins: { vitaminA: 0, vitaminC: 31, vitaminD: 0, vitaminE: 0.1, vitaminK: 2, vitaminB12: 0, folate: 3 },
        minerals: { calcium: 181, iron: 1.7, magnesium: 25, potassium: 401, zinc: 1.2 },
      },
      unit: '100g',
      servingSize: 10,
      caloriesPer100g: 149,
      isAllergen: false,
      tags: ['鳞茎类', '抗菌', '抗炎', '心血管健康', '大蒜素'],
    },
    // ==================== 水果 Fruits ====================
    {
      id: 'nutrition-apple',
      name: '苹果',
      category: '水果',
      subcategory: '仁果类',
      nutrition: {
        calories: 52,
        protein: 0.3,
        carbohydrates: 14,
        fat: 0.2,
        fiber: 2.4,
        sugar: 10,
        sodium: 1,
        saturatedFat: 0,
        cholesterol: 0,
        vitamins: { vitaminA: 3, vitaminC: 5, vitaminD: 0, vitaminE: 0.2, vitaminK: 2, vitaminB12: 0, folate: 4 },
        minerals: { calcium: 6, iron: 0.1, magnesium: 5, potassium: 107, zinc: 0 },
      },
      unit: '100g',
      servingSize: 200,
      caloriesPer100g: 52,
      isAllergen: false,
      tags: ['水果', '高纤维', '维生素C', '润肺', '通便'],
    },
    {
      id: 'nutrition-banana',
      name: '香蕉',
      category: '水果',
      subcategory: '热带水果',
      nutrition: {
        calories: 89,
        protein: 1.1,
        carbohydrates: 23,
        fat: 0.3,
        fiber: 2.6,
        sugar: 12,
        sodium: 1,
        saturatedFat: 0.1,
        cholesterol: 0,
        vitamins: { vitaminA: 3, vitaminC: 9, vitaminD: 0, vitaminE: 0.1, vitaminK: 0.5, vitaminB12: 0, folate: 20 },
        minerals: { calcium: 5, iron: 0.3, magnesium: 27, potassium: 358, zinc: 0.2 },
      },
      unit: '100g',
      servingSize: 150,
      caloriesPer100g: 89,
      isAllergen: false,
      tags: ['热带水果', '高钾', '高纤维', '能量', '润肠'],
    },
    {
      id: 'nutrition-orange',
      name: '橙子',
      category: '水果',
      subcategory: '柑橘类',
      nutrition: {
        calories: 47,
        protein: 0.9,
        carbohydrates: 12,
        fat: 0.1,
        fiber: 2.4,
        sugar: 9,
        sodium: 0,
        saturatedFat: 0,
        cholesterol: 0,
        vitamins: { vitaminA: 11, vitaminC: 53, vitaminD: 0, vitaminE: 0.2, vitaminK: 0, vitaminB12: 0, folate: 30 },
        minerals: { calcium: 40, iron: 0.1, magnesium: 10, potassium: 181, zinc: 0.1 },
      },
      unit: '100g',
      servingSize: 200,
      caloriesPer100g: 47,
      isAllergen: false,
      tags: ['柑橘类', '高维生素C', '高纤维', '美白', '维生素C之王'],
    },
    {
      id: 'nutrition-watermelon',
      name: '西瓜',
      category: '水果',
      subcategory: '瓜果类',
      nutrition: {
        calories: 30,
        protein: 0.6,
        carbohydrates: 8,
        fat: 0.2,
        fiber: 0.4,
        sugar: 6,
        sodium: 1,
        saturatedFat: 0,
        cholesterol: 0,
        vitamins: { vitaminA: 28, vitaminC: 6, vitaminD: 0, vitaminE: 0.1, vitaminK: 0.1, vitaminB12: 0, folate: 3 },
        minerals: { calcium: 7, iron: 0.2, magnesium: 10, potassium: 112, zinc: 0.1 },
      },
      unit: '100g',
      servingSize: 500,
      caloriesPer100g: 30,
      isAllergen: false,
      tags: ['瓜果类', '高水分', '清热', '解暑', '低热量'],
    },
    {
      id: 'nutrition-grape',
      name: '葡萄',
      category: '水果',
      subcategory: '浆果类',
      nutrition: {
        calories: 69,
        protein: 0.7,
        carbohydrates: 18,
        fat: 0.2,
        fiber: 0.9,
        sugar: 16,
        sodium: 2,
        saturatedFat: 0,
        cholesterol: 0,
        vitamins: { vitaminA: 3, vitaminC: 3, vitaminD: 0, vitaminE: 0.2, vitaminK: 15, vitaminB12: 0, folate: 2 },
        minerals: { calcium: 10, iron: 0.4, magnesium: 7, potassium: 191, zinc: 0.1 },
      },
      unit: '100g',
      servingSize: 150,
      caloriesPer100g: 69,
      isAllergen: false,
      tags: ['浆果类', '白藜芦醇', '抗氧化', '抗衰老', '花青素'],
    },
    {
      id: 'nutrition-strawberry',
      name: '草莓',
      category: '水果',
      subcategory: '浆果类',
      nutrition: {
        calories: 32,
        protein: 0.7,
        carbohydrates: 8,
        fat: 0.3,
        fiber: 2,
        sugar: 5,
        sodium: 1,
        saturatedFat: 0,
        cholesterol: 0,
        vitamins: { vitaminA: 1, vitaminC: 59, vitaminD: 0, vitaminE: 0.3, vitaminK: 2, vitaminB12: 0, folate: 24 },
        minerals: { calcium: 16, iron: 0.4, magnesium: 13, potassium: 153, zinc: 0.1 },
      },
      unit: '100g',
      servingSize: 150,
      caloriesPer100g: 32,
      isAllergen: false,
      tags: ['浆果类', '高维生素C', '高纤维', '美白', '抗氧化'],
    },
    {
      id: 'nutrition-pear',
      name: '梨',
      category: '水果',
      subcategory: '仁果类',
      nutrition: {
        calories: 38,
        protein: 0.4,
        carbohydrates: 10,
        fat: 0.1,
        fiber: 3.6,
        sugar: 6,
        sodium: 1,
        saturatedFat: 0,
        cholesterol: 0,
        vitamins: { vitaminA: 1, vitaminC: 4, vitaminD: 0, vitaminE: 0.1, vitaminK: 4, vitaminB12: 0, folate: 7 },
        minerals: { calcium: 9, iron: 0.2, magnesium: 8, potassium: 116, zinc: 0.1 },
      },
      unit: '100g',
      servingSize: 200,
      caloriesPer100g: 38,
      isAllergen: false,
      tags: ['仁果类', '高纤维', '润肺', '清热', '通便'],
    },
    {
      id: 'nutrition-mango',
      name: '芒果',
      category: '水果',
      subcategory: '热带水果',
      nutrition: {
        calories: 60,
        protein: 0.8,
        carbohydrates: 15,
        fat: 0.4,
        fiber: 1.6,
        sugar: 14,
        sodium: 1,
        saturatedFat: 0.1,
        cholesterol: 0,
        vitamins: { vitaminA: 54, vitaminC: 36, vitaminD: 0, vitaminE: 0.9, vitaminK: 4, vitaminB12: 0, folate: 71 },
        minerals: { calcium: 11, iron: 0.2, magnesium: 10, potassium: 168, zinc: 0.1 },
      },
      unit: '100g',
      servingSize: 200,
      caloriesPer100g: 60,
      isAllergen: false,
      tags: ['热带水果', '高维生素A', '高维生素C', '胡萝卜素', '护肤'],
    },
    {
      id: 'nutrition-kiwi',
      name: '猕猴桃',
      category: '水果',
      subcategory: '浆果类',
      nutrition: {
        calories: 61,
        protein: 1.1,
        carbohydrates: 15,
        fat: 0.5,
        fiber: 3,
        sugar: 9,
        sodium: 3,
        saturatedFat: 0,
        cholesterol: 0,
        vitamins: { vitaminA: 3, vitaminC: 93, vitaminD: 0, vitaminE: 1, vitaminK: 40, vitaminB12: 0, folate: 25 },
        minerals: { calcium: 34, iron: 0.3, magnesium: 17, potassium: 312, zinc: 0.1 },
      },
      unit: '100g',
      servingSize: 100,
      caloriesPer100g: 61,
      isAllergen: false,
      tags: ['浆果类', '高维生素C', '高纤维', '美白', '维生素C之王'],
    },
    {
      id: 'nutrition-pomegranate',
      name: '石榴',
      category: '水果',
      subcategory: '浆果类',
      nutrition: {
        calories: 83,
        protein: 1.7,
        carbohydrates: 19,
        fat: 1.2,
        fiber: 4,
        sugar: 14,
        sodium: 3,
        saturatedFat: 0.1,
        cholesterol: 0,
        vitamins: { vitaminA: 0, vitaminC: 10, vitaminD: 0, vitaminE: 0.6, vitaminK: 16, vitaminB12: 0, folate: 38 },
        minerals: { calcium: 10, iron: 0.3, magnesium: 7, potassium: 236, zinc: 0.2 },
      },
      unit: '100g',
      servingSize: 200,
      caloriesPer100g: 83,
      isAllergen: false,
      tags: ['浆果类', '抗氧化', '花青素', '美容', '抗衰老'],
    },
    // ==================== 蛋白质类 Protein ====================
    {
      id: 'nutrition-chicken-breast',
      name: '鸡胸肉',
      category: '肉类',
      subcategory: '禽类',
      nutrition: {
        calories: 165,
        protein: 31,
        carbohydrates: 0,
        fat: 3.6,
        fiber: 0,
        sugar: 0,
        sodium: 74,
        saturatedFat: 1,
        cholesterol: 85,
        vitamins: { vitaminA: 1, vitaminC: 0, vitaminD: 0, vitaminE: 0.3, vitaminK: 0, vitaminB12: 0.3, folate: 4 },
        minerals: { calcium: 15, iron: 1, magnesium: 29, potassium: 256, zinc: 1 },
      },
      unit: '100g',
      servingSize: 150,
      caloriesPer100g: 165,
      isAllergen: false,
      tags: ['禽类', '高蛋白', '低脂肪', '增肌', '鸡胸肉'],
    },
    {
      id: 'nutrition-chicken-thigh',
      name: '鸡腿肉',
      category: '肉类',
      subcategory: '禽类',
      nutrition: {
        calories: 209,
        protein: 26,
        carbohydrates: 0,
        fat: 11,
        fiber: 0,
        sugar: 0,
        sodium: 87,
        saturatedFat: 3,
        cholesterol: 93,
        vitamins: { vitaminA: 2, vitaminC: 0, vitaminD: 0, vitaminE: 0.4, vitaminK: 0, vitaminB12: 0.4, folate: 6 },
        minerals: { calcium: 13, iron: 1.1, magnesium: 26, potassium: 265, zinc: 1.2 },
      },
      unit: '100g',
      servingSize: 150,
      caloriesPer100g: 209,
      isAllergen: false,
      tags: ['禽类', '高蛋白', '铁', 'B族维生素'],
    },
    {
      id: 'nutrition-beef',
      name: '牛肉',
      category: '肉类',
      subcategory: '红肉',
      nutrition: {
        calories: 250,
        protein: 26,
        carbohydrates: 0,
        fat: 15,
        fiber: 0,
        sugar: 0,
        sodium: 72,
        saturatedFat: 6,
        cholesterol: 90,
        vitamins: { vitaminA: 0, vitaminC: 0, vitaminD: 0, vitaminE: 0.2, vitaminK: 1, vitaminB12: 2.6, folate: 6 },
        minerals: { calcium: 18, iron: 2.6, magnesium: 21, potassium: 318, zinc: 5.5 },
      },
      unit: '100g',
      servingSize: 150,
      caloriesPer100g: 250,
      isAllergen: false,
      tags: ['红肉', '高蛋白', '高铁', '锌', 'B12', '补血'],
    },
    {
      id: 'nutrition-pork',
      name: '猪肉',
      category: '肉类',
      subcategory: '红肉',
      nutrition: {
        calories: 242,
        protein: 27,
        carbohydrates: 0,
        fat: 14,
        fiber: 0,
        sugar: 0,
        sodium: 62,
        saturatedFat: 5,
        cholesterol: 86,
        vitamins: { vitaminA: 0, vitaminC: 0, vitaminD: 0, vitaminE: 0.2, vitaminK: 0, vitaminB12: 0.5, folate: 5 },
        minerals: { calcium: 11, iron: 1, magnesium: 25, potassium: 351, zinc: 2.5 },
      },
      unit: '100g',
      servingSize: 150,
      caloriesPer100g: 242,
      isAllergen: false,
      tags: ['红肉', '高蛋白', 'B族维生素', '能量'],
    },
    {
      id: 'nutrition-salmon',
      name: '三文鱼',
      category: '水产',
      subcategory: '鱼类',
      nutrition: {
        calories: 208,
        protein: 20,
        carbohydrates: 0,
        fat: 13,
        fiber: 0,
        sugar: 0,
        sodium: 59,
        saturatedFat: 3,
        cholesterol: 55,
        vitamins: { vitaminA: 50, vitaminC: 0, vitaminD: 11, vitaminE: 1.8, vitaminK: 0, vitaminB12: 3.2, folate: 7 },
        minerals: { calcium: 12, iron: 0.3, magnesium: 29, potassium: 363, zinc: 0.6 },
      },
      unit: '100g',
      servingSize: 150,
      caloriesPer100g: 208,
      isAllergen: true,
      allergenType: ['fish'],
      tags: ['鱼类', 'Omega-3', '高蛋白', '维生素D', '心脏健康', 'DHA'],
    },
    {
      id: 'nutrition-tilapia',
      name: '罗非鱼',
      category: '水产',
      subcategory: '鱼类',
      nutrition: {
        calories: 128,
        protein: 26,
        carbohydrates: 0,
        fat: 2.7,
        fiber: 0,
        sugar: 0,
        sodium: 52,
        saturatedFat: 1,
        cholesterol: 50,
        vitamins: { vitaminA: 0, vitaminC: 0, vitaminD: 0, vitaminE: 0.3, vitaminK: 1, vitaminB12: 0.5, folate: 12 },
        minerals: { calcium: 17, iron: 0.4, magnesium: 32, potassium: 356, zinc: 0.5 },
      },
      unit: '100g',
      servingSize: 200,
      caloriesPer100g: 128,
      isAllergen: true,
      allergenType: ['fish'],
      tags: ['鱼类', '高蛋白', '低脂肪', '低热量', '嫩滑'],
    },
    {
      id: 'nutrition-shrimp',
      name: '虾',
      category: '水产',
      subcategory: '甲壳类',
      nutrition: {
        calories: 99,
        protein: 24,
        carbohydrates: 0.2,
        fat: 0.3,
        fiber: 0,
        sugar: 0,
        sodium: 111,
        saturatedFat: 0.1,
        cholesterol: 189,
        vitamins: { vitaminA: 54, vitaminC: 0, vitaminD: 0, vitaminE: 0.1, vitaminK: 0, vitaminB12: 1.1, folate: 2 },
        minerals: { calcium: 70, iron: 0.5, magnesium: 36, potassium: 259, zinc: 1.4 },
      },
      unit: '100g',
      servingSize: 150,
      caloriesPer100g: 99,
      isAllergen: true,
      allergenType: ['shellfish'],
      tags: ['甲壳类', '高蛋白', '低脂肪', '高钙', '矿物质'],
    },
    {
      id: 'nutrition-crab',
      name: '螃蟹',
      category: '水产',
      subcategory: '甲壳类',
      nutrition: {
        calories: 97,
        protein: 19,
        carbohydrates: 0,
        fat: 1.5,
        fiber: 0,
        sugar: 0,
        sodium: 270,
        saturatedFat: 0.3,
        cholesterol: 100,
        vitamins: { vitaminA: 2, vitaminC: 0, vitaminD: 0, vitaminE: 0.5, vitaminK: 5, vitaminB12: 2.5, folate: 45 },
        minerals: { calcium: 126, iron: 0.5, magnesium: 42, potassium: 234, zinc: 2.8 },
      },
      unit: '100g',
      servingSize: 200,
      caloriesPer100g: 97,
      isAllergen: true,
      allergenType: ['shellfish'],
      tags: ['甲壳类', '高蛋白', '高钙', '矿物质', '蟹黄'],
    },
    {
      id: 'nutrition-egg',
      name: '鸡蛋',
      category: '蛋类',
      subcategory: '蛋类',
      nutrition: {
        calories: 155,
        protein: 13,
        carbohydrates: 1.1,
        fat: 11,
        fiber: 0,
        sugar: 1.1,
        sodium: 124,
        saturatedFat: 3.3,
        cholesterol: 373,
        vitamins: { vitaminA: 160, vitaminC: 0, vitaminD: 2, vitaminE: 1, vitaminK: 0.3, vitaminB12: 0.9, folate: 22 },
        minerals: { calcium: 56, iron: 1.8, magnesium: 12, potassium: 138, zinc: 1.3 },
      },
      unit: '100g',
      servingSize: 50,
      caloriesPer100g: 155,
      isAllergen: true,
      allergenType: ['eggs'],
      tags: ['蛋类', '完全蛋白', '高营养', '胆碱', '叶黄素'],
    },
    {
      id: 'nutrition-egg-white',
      name: '蛋白',
      category: '蛋类',
      subcategory: '蛋类',
      nutrition: {
        calories: 52,
        protein: 11,
        carbohydrates: 0.7,
        fat: 0.2,
        fiber: 0,
        sugar: 0.7,
        sodium: 166,
        saturatedFat: 0,
        cholesterol: 0,
        vitamins: { vitaminA: 0, vitaminC: 0, vitaminD: 0, vitaminE: 0, vitaminK: 0, vitaminB12: 0.1, folate: 4 },
        minerals: { calcium: 7, iron: 0.1, magnesium: 11, potassium: 163, zinc: 0 },
      },
      unit: '100g',
      servingSize: 100,
      caloriesPer100g: 52,
      isAllergen: true,
      allergenType: ['eggs'],
      tags: ['蛋类', '高蛋白', '低热量', '低脂肪', '增肌'],
    },
    {
      id: 'nutrition-tofu',
      name: '豆腐',
      category: '豆制品',
      subcategory: '豆制品',
      nutrition: {
        calories: 76,
        protein: 8,
        carbohydrates: 2,
        fat: 4,
        fiber: 0.3,
        sugar: 0,
        sodium: 7,
        saturatedFat: 0.7,
        cholesterol: 0,
        vitamins: { vitaminA: 0, vitaminC: 0, vitaminD: 0, vitaminE: 0.1, vitaminK: 2, vitaminB12: 0, folate: 15 },
        minerals: { calcium: 350, iron: 2.7, magnesium: 58, potassium: 121, zinc: 0.8 },
      },
      unit: '100g',
      servingSize: 150,
      caloriesPer100g: 76,
      isAllergen: true,
      allergenType: ['soy'],
      tags: ['豆制品', '高蛋白', '高钙', '植物蛋白', '异黄酮'],
    },
    {
      id: 'nutrition-soy-milk',
      name: '豆浆',
      category: '豆制品',
      subcategory: '饮料',
      nutrition: {
        calories: 31,
        protein: 3,
        carbohydrates: 1,
        fat: 2,
        fiber: 0,
        sugar: 0,
        sodium: 1,
        saturatedFat: 0.2,
        cholesterol: 0,
        vitamins: { vitaminA: 0, vitaminC: 0, vitaminD: 0, vitaminE: 0.1, vitaminK: 2, vitaminB12: 0, folate: 9 },
        minerals: { calcium: 10, iron: 0.4, magnesium: 15, potassium: 120, zinc: 0.2 },
      },
      unit: '100ml',
      servingSize: 250,
      caloriesPer100g: 31,
      isAllergen: true,
      allergenType: ['soy'],
      tags: ['豆制品', '植物蛋白', '大豆异黄酮', '低脂'],
    },
    {
      id: 'nutrition-edamame',
      name: '毛豆',
      category: '豆制品',
      subcategory: '豆类',
      nutrition: {
        calories: 121,
        protein: 11,
        carbohydrates: 10,
        fat: 5,
        fiber: 5,
        sugar: 2,
        sodium: 9,
        saturatedFat: 0.5,
        cholesterol: 0,
        vitamins: { vitaminA: 0, vitaminC: 10, vitaminD: 0, vitaminE: 0, vitaminK: 20, vitaminB12: 0, folate: 181 },
        minerals: { calcium: 63, iron: 1.3, magnesium: 64, potassium: 420, zinc: 1 },
      },
      unit: '100g',
      servingSize: 100,
      caloriesPer100g: 121,
      isAllergen: true,
      allergenType: ['soy'],
      tags: ['豆类', '高蛋白', '高纤维', '叶酸', '异黄酮'],
    },
    // ==================== 乳制品 Dairy ====================
    {
      id: 'nutrition-milk',
      name: '牛奶',
      category: '乳制品',
      subcategory: '液态奶',
      nutrition: {
        calories: 61,
        protein: 3.4,
        carbohydrates: 5,
        fat: 3.3,
        fiber: 0,
        sugar: 5,
        sodium: 43,
        saturatedFat: 1.9,
        cholesterol: 10,
        vitamins: { vitaminA: 46, vitaminC: 0, vitaminD: 1, vitaminE: 0.1, vitaminK: 0, vitaminB12: 0.5, folate: 5 },
        minerals: { calcium: 125, iron: 0, magnesium: 10, potassium: 143, zinc: 0.4 },
      },
      unit: '100ml',
      servingSize: 250,
      caloriesPer100g: 61,
      isAllergen: true,
      allergenType: ['dairy'],
      tags: ['乳制品', '高钙', '蛋白质', '维生素D', '骨骼健康'],
    },
    {
      id: 'nutrition-greek-yogurt',
      name: '希腊酸奶',
      category: '乳制品',
      subcategory: '发酵乳',
      nutrition: {
        calories: 97,
        protein: 9,
        carbohydrates: 4,
        fat: 5,
        fiber: 0,
        sugar: 3,
        sodium: 36,
        saturatedFat: 3,
        cholesterol: 15,
        vitamins: { vitaminA: 40, vitaminC: 0, vitaminD: 0, vitaminE: 0.1, vitaminK: 0, vitaminB12: 0.8, folate: 12 },
        minerals: { calcium: 110, iron: 0, magnesium: 11, potassium: 141, zinc: 0.5 },
      },
      unit: '100g',
      servingSize: 170,
      caloriesPer100g: 97,
      isAllergen: true,
      allergenType: ['dairy'],
      tags: ['发酵乳', '高蛋白', '益生菌', '高钙', '饱腹感'],
    },
    {
      id: 'nutrition-yogurt',
      name: '酸奶',
      category: '乳制品',
      subcategory: '发酵乳',
      nutrition: {
        calories: 63,
        protein: 3.5,
        carbohydrates: 7,
        fat: 1.5,
        fiber: 0,
        sugar: 6,
        sodium: 36,
        saturatedFat: 0.9,
        cholesterol: 5,
        vitamins: { vitaminA: 26, vitaminC: 0, vitaminD: 0, vitaminE: 0.1, vitaminK: 0, vitaminB12: 0.4, folate: 8 },
        minerals: { calcium: 100, iron: 0, magnesium: 9, potassium: 141, zinc: 0.4 },
      },
      unit: '100g',
      servingSize: 200,
      caloriesPer100g: 63,
      isAllergen: true,
      allergenType: ['dairy'],
      tags: ['发酵乳', '益生菌', '高钙', '助消化', '肠道健康'],
    },
    {
      id: 'nutrition-cheese',
      name: '奶酪',
      category: '乳制品',
      subcategory: '干酪',
      nutrition: {
        calories: 402,
        protein: 25,
        carbohydrates: 1.3,
        fat: 33,
        fiber: 0,
        sugar: 0.5,
        sodium: 621,
        saturatedFat: 21,
        cholesterol: 105,
        vitamins: { vitaminA: 265, vitaminC: 0, vitaminD: 0, vitaminE: 0.3, vitaminK: 2, vitaminB12: 0.8, folate: 18 },
        minerals: { calcium: 721, iron: 0.7, magnesium: 28, potassium: 98, zinc: 3 },
      },
      unit: '100g',
      servingSize: 30,
      caloriesPer100g: 402,
      isAllergen: true,
      allergenType: ['dairy'],
      tags: ['干酪', '高钙', '高蛋白', '高脂肪', 'B12'],
    },
    // ==================== 坚果 Seeds & Nuts ====================
    {
      id: 'nutrition-almonds',
      name: '杏仁',
      category: '坚果',
      subcategory: '树坚果',
      nutrition: {
        calories: 579,
        protein: 21,
        carbohydrates: 22,
        fat: 50,
        fiber: 12,
        sugar: 4,
        sodium: 1,
        saturatedFat: 4,
        cholesterol: 0,
        vitamins: { vitaminA: 0, vitaminC: 0, vitaminD: 0, vitaminE: 26, vitaminK: 0, vitaminB12: 0, folate: 44 },
        minerals: { calcium: 269, iron: 4, magnesium: 270, potassium: 733, zinc: 3 },
      },
      unit: '100g',
      servingSize: 30,
      caloriesPer100g: 579,
      isAllergen: true,
      allergenType: ['tree nuts'],
      tags: ['坚果', '维生素E', '镁', '健康脂肪', '维生素E之王'],
    },
    {
      id: 'nutrition-walnuts',
      name: '核桃',
      category: '坚果',
      subcategory: '树坚果',
      nutrition: {
        calories: 654,
        protein: 15,
        carbohydrates: 14,
        fat: 65,
        fiber: 7,
        sugar: 3,
        sodium: 2,
        saturatedFat: 6,
        cholesterol: 0,
        vitamins: { vitaminA: 1, vitaminC: 2, vitaminD: 0, vitaminE: 1, vitaminK: 2, vitaminB12: 0, folate: 98 },
        minerals: { calcium: 98, iron: 2.9, magnesium: 158, potassium: 441, zinc: 3 },
      },
      unit: '100g',
      servingSize: 30,
      caloriesPer100g: 654,
      isAllergen: true,
      allergenType: ['tree nuts'],
      tags: ['坚果', 'Omega-3', '大脑食物', '健康脂肪', '抗氧化'],
    },
    {
      id: 'nutrition-peanuts',
      name: '花生',
      category: '坚果',
      subcategory: '豆科',
      nutrition: {
        calories: 567,
        protein: 26,
        carbohydrates: 16,
        fat: 49,
        fiber: 9,
        sugar: 4,
        sodium: 18,
        saturatedFat: 7,
        cholesterol: 0,
        vitamins: { vitaminA: 0, vitaminC: 0, vitaminD: 0, vitaminE: 8, vitaminK: 0, vitaminB12: 0, folate: 240 },
        minerals: { calcium: 92, iron: 4.6, magnesium: 168, potassium: 705, zinc: 3.3 },
      },
      unit: '100g',
      servingSize: 30,
      caloriesPer100g: 567,
      isAllergen: true,
      allergenType: ['peanuts'],
      tags: ['坚果', '高蛋白', '高纤维', '维生素E', '白藜芦醇'],
    },
    {
      id: 'nutrition-cashews',
      name: '腰果',
      category: '坚果',
      subcategory: '树坚果',
      nutrition: {
        calories: 553,
        protein: 18,
        carbohydrates: 30,
        fat: 44,
        fiber: 3,
        sugar: 6,
        sodium: 12,
        saturatedFat: 8,
        cholesterol: 0,
        vitamins: { vitaminA: 0, vitaminC: 0, vitaminD: 0, vitaminE: 0.9, vitaminK: 34, vitaminB12: 0, folate: 20 },
        minerals: { calcium: 37, iron: 6.7, magnesium: 292, potassium: 660, zinc: 5.8 },
      },
      unit: '100g',
      servingSize: 30,
      caloriesPer100g: 553,
      isAllergen: true,
      allergenType: ['tree nuts'],
      tags: ['坚果', '高镁', '高锌', '铜', '硒'],
    },
    {
      id: 'nutrition-sunflower-seeds',
      name: '葵花籽',
      category: '坚果',
      subcategory: '种子',
      nutrition: {
        calories: 584,
        protein: 21,
        carbohydrates: 20,
        fat: 51,
        fiber: 8,
        sugar: 2.6,
        sodium: 9,
        saturatedFat: 5,
        cholesterol: 0,
        vitamins: { vitaminA: 3, vitaminC: 1, vitaminD: 0, vitaminE: 35, vitaminK: 0, vitaminB12: 0, folate: 227 },
        minerals: { calcium: 78, iron: 5, magnesium: 325, potassium: 645, zinc: 5 },
      },
      unit: '100g',
      servingSize: 30,
      caloriesPer100g: 584,
      isAllergen: false,
      tags: ['种子', '维生素E', '镁', '硒', '抗氧化'],
    },
    {
      id: 'nutrition-pumpkin-seeds',
      name: '南瓜子',
      category: '坚果',
      subcategory: '种子',
      nutrition: {
        calories: 559,
        protein: 30,
        carbohydrates: 11,
        fat: 49,
        fiber: 6,
        sugar: 1.4,
        sodium: 7,
        saturatedFat: 9,
        cholesterol: 0,
        vitamins: { vitaminA: 1, vitaminC: 2, vitaminD: 0, vitaminE: 2.2, vitaminK: 7, vitaminB12: 0, folate: 58 },
        minerals: { calcium: 46, iron: 8.8, magnesium: 592, potassium: 809, zinc: 7.8 },
      },
      unit: '100g',
      servingSize: 30,
      caloriesPer100g: 559,
      isAllergen: false,
      tags: ['种子', '高镁', '高锌', '高蛋白', '铁'],
    },
    // ==================== 油脂 Oils ====================
    {
      id: 'nutrition-olive-oil',
      name: '橄榄油',
      category: '油脂',
      subcategory: '植物油',
      nutrition: {
        calories: 884,
        protein: 0,
        carbohydrates: 0,
        fat: 100,
        fiber: 0,
        sugar: 0,
        sodium: 2,
        saturatedFat: 14,
        cholesterol: 0,
        vitamins: { vitaminA: 0, vitaminC: 0, vitaminD: 0, vitaminE: 14, vitaminK: 60, vitaminB12: 0, folate: 0 },
        minerals: { calcium: 1, iron: 0.1, magnesium: 0, potassium: 1, zinc: 0 },
      },
      unit: '100ml',
      servingSize: 15,
      caloriesPer100g: 884,
      isAllergen: false,
      tags: ['油脂', '健康脂肪', '维生素E', '地中海饮食', '单不饱和脂肪酸'],
    },
    {
      id: 'nutrition-coconut-oil',
      name: '椰子油',
      category: '油脂',
      subcategory: '植物油',
      nutrition: {
        calories: 892,
        protein: 0,
        carbohydrates: 0,
        fat: 99,
        fiber: 0,
        sugar: 0,
        sodium: 0,
        saturatedFat: 87,
        cholesterol: 0,
        vitamins: { vitaminA: 0, vitaminC: 0, vitaminD: 0, vitaminE: 0.1, vitaminK: 0.5, vitaminB12: 0, folate: 0 },
        minerals: { calcium: 0, iron: 0, magnesium: 0, potassium: 0, zinc: 0 },
      },
      unit: '100ml',
      servingSize: 15,
      caloriesPer100g: 892,
      isAllergen: false,
      tags: ['油脂', '中链脂肪酸', '饱和脂肪', '椰子'],
    },
    {
      id: 'nutrition-sesame-oil',
      name: '芝麻油',
      category: '油脂',
      subcategory: '植物油',
      nutrition: {
        calories: 884,
        protein: 0,
        carbohydrates: 0,
        fat: 100,
        fiber: 0,
        sugar: 0,
        sodium: 0,
        saturatedFat: 14,
        cholesterol: 0,
        vitamins: { vitaminA: 0, vitaminC: 0, vitaminD: 0, vitaminE: 0.5, vitaminK: 0, vitaminB12: 0, folate: 0 },
        minerals: { calcium: 0, iron: 0, magnesium: 0, potassium: 0, zinc: 0 },
      },
      unit: '100ml',
      servingSize: 10,
      caloriesPer100g: 884,
      isAllergen: false,
      tags: ['油脂', '芝麻', '香油', '风味油', '抗氧化'],
    },
    // ==================== 其他 Others ====================
    {
      id: 'nutrition-honey',
      name: '蜂蜜',
      category: '其他',
      subcategory: '甜味剂',
      nutrition: {
        calories: 304,
        protein: 0.3,
        carbohydrates: 82,
        fat: 0,
        fiber: 0,
        sugar: 82,
        sodium: 4,
        saturatedFat: 0,
        cholesterol: 0,
        vitamins: { vitaminA: 0, vitaminC: 0.5, vitaminD: 0, vitaminE: 0, vitaminK: 0, vitaminB12: 0, folate: 2 },
        minerals: { calcium: 6, iron: 0.4, magnesium: 2, potassium: 52, zinc: 0.2 },
      },
      unit: '100g',
      servingSize: 20,
      caloriesPer100g: 304,
      isAllergen: false,
      tags: ['甜味剂', '天然糖', '抗菌', '能量', '润喉'],
    },
    {
      id: 'nutrition-goji-berry',
      name: '枸杞',
      category: '其他',
      subcategory: '药食同源',
      nutrition: {
        calories: 349,
        protein: 13,
        carbohydrates: 64,
        fat: 0.4,
        fiber: 17,
        sugar: 46,
        sodium: 252,
        saturatedFat: 0,
        cholesterol: 0,
        vitamins: { vitaminA: 26829, vitaminC: 48, vitaminD: 0, vitaminE: 0, vitaminK: 212, vitaminB12: 0, folate: 20 },
        minerals: { calcium: 60, iron: 5.4, magnesium: 96, potassium: 434, zinc: 1.5 },
      },
      unit: '100g',
      servingSize: 20,
      caloriesPer100g: 349,
      isAllergen: false,
      tags: ['药食同源', '高维生素A', '胡萝卜素', '护眼', '滋补'],
    },
    {
      id: 'nutrition-red-dates',
      name: '红枣',
      category: '其他',
      subcategory: '药食同源',
      nutrition: {
        calories: 264,
        protein: 1.4,
        carbohydrates: 67,
        fat: 0.3,
        fiber: 7,
        sugar: 64,
        sodium: 3,
        saturatedFat: 0,
        cholesterol: 0,
        vitamins: { vitaminA: 2, vitaminC: 14, vitaminD: 0, vitaminE: 0.1, vitaminK: 2, vitaminB12: 0, folate: 9 },
        minerals: { calcium: 39, iron: 1.5, magnesium: 23, potassium: 607, zinc: 0.4 },
      },
      unit: '100g',
      servingSize: 50,
      caloriesPer100g: 264,
      isAllergen: false,
      tags: ['药食同源', '补血', '养血', '安神', '能量'],
    },
    {
      id: 'nutrition-yam',
      name: '山药',
      category: '蔬菜',
      subcategory: '根茎类',
      nutrition: {
        calories: 82,
        protein: 1.9,
        carbohydrates: 20,
        fat: 0.2,
        fiber: 4,
        sugar: 0.9,
        sodium: 9,
        saturatedFat: 0.1,
        cholesterol: 0,
        vitamins: { vitaminA: 1, vitaminC: 5, vitaminD: 0, vitaminE: 0.1, vitaminK: 2, vitaminB12: 0, folate: 23 },
        minerals: { calcium: 16, iron: 0.3, magnesium: 21, potassium: 302, zinc: 0.2 },
      },
      unit: '100g',
      servingSize: 200,
      caloriesPer100g: 82,
      isAllergen: false,
      tags: ['根茎类', '健脾', '养胃', '高纤维', '黏液蛋白'],
    },
    {
      id: 'nutrition-lotus-root',
      name: '莲藕',
      category: '蔬菜',
      subcategory: '根茎类',
      nutrition: {
        calories: 73,
        protein: 2,
        carbohydrates: 17,
        fat: 0.2,
        fiber: 4,
        sugar: 2,
        sodium: 16,
        saturatedFat: 0,
        cholesterol: 0,
        vitamins: { vitaminA: 0, vitaminC: 28, vitaminD: 0, vitaminE: 0.1, vitaminK: 0, vitaminB12: 0, folate: 26 },
        minerals: { calcium: 26, iron: 1.2, magnesium: 22, potassium: 293, zinc: 0.3 },
      },
      unit: '100g',
      servingSize: 150,
      caloriesPer100g: 73,
      isAllergen: false,
      tags: ['根茎类', '高维生素C', '高纤维', '清热', '润肺'],
    },
    {
      id: 'nutrition-winter-melon',
      name: '冬瓜',
      category: '蔬菜',
      subcategory: '瓜类',
      nutrition: {
        calories: 12,
        protein: 0.4,
        carbohydrates: 3,
        fat: 0.1,
        fiber: 1,
        sugar: 1.7,
        sodium: 1,
        saturatedFat: 0,
        cholesterol: 0,
        vitamins: { vitaminA: 0, vitaminC: 11, vitaminD: 0, vitaminE: 0, vitaminK: 0, vitaminB12: 0, folate: 6 },
        minerals: { calcium: 14, iron: 0.2, magnesium: 8, potassium: 111, zinc: 0.1 },
      },
      unit: '100g',
      servingSize: 500,
      caloriesPer100g: 12,
      isAllergen: false,
      tags: ['瓜类', '低热量', '高水分', '清热', '利尿'],
    },
    {
      id: 'nutrition-wonton-wrapper',
      name: '馄饨皮',
      category: '谷类',
      subcategory: '主食',
      nutrition: {
        calories: 218,
        protein: 8,
        carbohydrates: 40,
        fat: 2,
        fiber: 1.5,
        sugar: 1,
        sodium: 350,
        saturatedFat: 0.3,
        cholesterol: 0,
        vitamins: { vitaminA: 0, vitaminC: 0, vitaminD: 0, vitaminE: 0.1, vitaminK: 0, vitaminB12: 0, folate: 120 },
        minerals: { calcium: 20, iron: 1.2, magnesium: 20, potassium: 100, zinc: 0.8 },
      },
      unit: '100g',
      servingSize: 100,
      caloriesPer100g: 218,
      isAllergen: true,
      allergenType: ['gluten'],
      tags: ['主食', '碳水化合物', '面食'],
    },
  ];

  // Populate the database
  for (const food of foods) {
    FOOD_DATABASE.set(food.id, food);
  }
}

export class NutritionDB {
  private db: Map<string, Food>;

  constructor() {
    this.db = FOOD_DATABASE;
  }

  search(query: string, limit: number = 10): Food[] {
    const results: Food[] = [];
    for (const food of this.db.values()) {
      if (
        food.name.toLowerCase().includes(query.toLowerCase()) ||
        food.category.toLowerCase().includes(query.toLowerCase()) ||
        food.tags.some(tag => tag.toLowerCase().includes(query.toLowerCase()))
      ) {
        results.push(food);
        if (results.length >= limit) break;
      }
    }
    return results;
  }

  getById(id: string): Food | undefined {
    return this.db.get(id);
  }

  getByCategory(category: string): Food[] {
    return Array.from(this.db.values()).filter(f => f.category === category);
  }

  getAll(): Food[] {
    return Array.from(this.db.values());
  }

  calculateMealNutritionSync(foods: Array<{ foodId: string; amount: number }>): NutritionInfo {
    let total: NutritionInfo = {
      calories: 0,
      protein: 0,
      carbohydrates: 0,
      fat: 0,
      fiber: 0,
      sugar: 0,
      sodium: 0,
      saturatedFat: 0,
      cholesterol: 0,
      vitamins: { vitaminA: 0, vitaminC: 0, vitaminD: 0, vitaminE: 0, vitaminK: 0, vitaminB12: 0, folate: 0 },
      minerals: { calcium: 0, iron: 0, magnesium: 0, potassium: 0, zinc: 0 },
    };

    for (const item of foods) {
      const food = this.db.get(item.foodId);
      if (food) {
        const ratio = item.amount / food.servingSize;
        total = {
          calories: total.calories + food.nutrition.calories * ratio,
          protein: total.protein + food.nutrition.protein * ratio,
          carbohydrates: total.carbohydrates + food.nutrition.carbohydrates * ratio,
          fat: total.fat + food.nutrition.fat * ratio,
          fiber: total.fiber + food.nutrition.fiber * ratio,
          sugar: total.sugar + food.nutrition.sugar * ratio,
          sodium: total.sodium + food.nutrition.sodium * ratio,
          saturatedFat: total.saturatedFat + food.nutrition.saturatedFat * ratio,
          cholesterol: total.cholesterol + food.nutrition.cholesterol * ratio,
          vitamins: {
            vitaminA: total.vitamins.vitaminA + food.nutrition.vitamins.vitaminA * ratio,
            vitaminC: total.vitamins.vitaminC + food.nutrition.vitamins.vitaminC * ratio,
            vitaminD: total.vitamins.vitaminD + food.nutrition.vitamins.vitaminD * ratio,
            vitaminE: total.vitamins.vitaminE + food.nutrition.vitamins.vitaminE * ratio,
            vitaminK: total.vitamins.vitaminK + food.nutrition.vitamins.vitaminK * ratio,
            vitaminB12: total.vitamins.vitaminB12 + food.nutrition.vitamins.vitaminB12 * ratio,
            folate: total.vitamins.folate + food.nutrition.vitamins.folate * ratio,
          },
          minerals: {
            calcium: total.minerals.calcium + food.nutrition.minerals.calcium * ratio,
            iron: total.minerals.iron + food.nutrition.minerals.iron * ratio,
            magnesium: total.minerals.magnesium + food.nutrition.minerals.magnesium * ratio,
            potassium: total.minerals.potassium + food.nutrition.minerals.potassium * ratio,
            zinc: total.minerals.zinc + food.nutrition.minerals.zinc * ratio,
          },
        };
      }
    }
    return total;
  }

  analyzeNutrientBalance(info: NutritionInfo, targets: { calories: number; protein: number; fat: number; carbs: number }): {
    status: 'good' | 'low' | 'high';
    message: string;
    details: { nutrient: string; current: number; target: number; percentage: number }[];
  } {
    const details = [
      { nutrient: '热量', current: info.calories, target: targets.calories },
      { nutrient: '蛋白质', current: info.protein, target: targets.protein },
      { nutrient: '脂肪', current: info.fat, target: targets.fat },
      { nutrient: '碳水化合物', current: info.carbohydrates, target: targets.carbs },
    ];

    const percentages = details.map(d => ({
      ...d,
      percentage: d.target > 0 ? (d.current / d.target) * 100 : 0,
    }));

    const avgPercentage = percentages.reduce((sum, d) => sum + d.percentage, 0) / percentages.length;
    let status: 'good' | 'low' | 'high' = 'good';
    if (avgPercentage < 80) status = 'low';
    else if (avgPercentage > 120) status = 'high';

    let message = '';
    if (status === 'good') {
      message = '营养摄入均衡，搭配合理';
    } else if (status === 'low') {
      message = '营养摄入不足，建议增加摄入量';
    } else {
      message = '营养摄入过量，建议适当减少';
    }

    return { status, message, details: percentages };
  }

  async searchFoods(params: { query?: string; category?: string; minProtein?: number; minFiber?: number; maxCalories?: number; tags?: string[] }): Promise<Food[]> {
    let results = this.getAll();

    if (params.query) {
      const q = params.query.toLowerCase();
      results = results.filter(f =>
        f.name.toLowerCase().includes(q) ||
        f.category.toLowerCase().includes(q) ||
        f.tags.some(t => t.toLowerCase().includes(q))
      );
    }

    if (params.category) {
      results = results.filter(f => f.category === params.category);
    }

    if (params.minProtein !== undefined) {
      results = results.filter(f => f.nutrition.protein >= params.minProtein!);
    }

    if (params.minFiber !== undefined) {
      results = results.filter(f => f.nutrition.fiber >= params.minFiber!);
    }

    if (params.maxCalories !== undefined) {
      results = results.filter(f => f.nutrition.calories <= params.maxCalories!);
    }

    if (params.tags && params.tags.length > 0) {
      results = results.filter(f => params.tags!.some(t => f.tags.includes(t)));
    }

    return results.slice(0, 50);
  }

  async getFoodById(id: string): Promise<Food | undefined> {
    return this.db.get(id);
  }

  async getNutritionInfo(id: string, servingSize?: number): Promise<NutritionInfo | undefined> {
    const food = this.db.get(id);
    if (!food) return undefined;

    const info = { ...food.nutrition };
    if (servingSize && servingSize !== food.servingSize) {
      const ratio = servingSize / food.servingSize;
      info.calories = info.calories * ratio;
      info.protein = info.protein * ratio;
      info.carbohydrates = info.carbohydrates * ratio;
      info.fat = info.fat * ratio;
      info.fiber = info.fiber * ratio;
      info.sugar = info.sugar * ratio;
      info.sodium = info.sodium * ratio;
      info.saturatedFat = info.saturatedFat * ratio;
      info.cholesterol = info.cholesterol * ratio;
    }
    return info;
  }

  async calculateMealNutrition(foods: Array<{ id: string; amount: number }>): Promise<NutritionInfo> {
    const mapped = foods.map(f => ({ foodId: f.id, amount: f.amount }));
    return this.calculateMealNutritionSync(mapped);
  }

  async getCategories(): Promise<string[]> {
    const categories = new Set<string>();
    for (const food of this.db.values()) {
      categories.add(food.category);
    }
    return Array.from(categories);
  }

  async getHighInNutrient(nutrient: string, limit: number = 10): Promise<Food[]> {
    const all = this.getAll();
    const sorted = all.sort((a, b) => {
      const aVal = (a.nutrition as any)[nutrient] || 0;
      const bVal = (b.nutrition as any)[nutrient] || 0;
      return bVal - aVal;
    });
    return sorted.slice(0, limit);
  }
}

// MCP wrapper for nutrition database
export const nutritionDatabaseMCP = {
  searchFoods: (params: { query?: string; category?: string; minProtein?: number; minFiber?: number; maxCalories?: number; tags?: string[] }) =>
    nutritionDB.searchFoods(params),

  getFoodById: (id: string) => nutritionDB.getFoodById(id),

  getNutritionInfo: (id: string, servingSize?: number) => nutritionDB.getNutritionInfo(id, servingSize),

  calculateMealNutrition: (foods: Array<{ id: string; amount: number }>) =>
    nutritionDB.calculateMealNutrition(foods),

  getCategories: () => nutritionDB.getCategories(),

  getHighInNutrient: (nutrient: string, limit?: number) => nutritionDB.getHighInNutrient(nutrient, limit),
};

export const nutritionDB = new NutritionDB();

