/**
 * HowToCook Recipe Database (300+ Recipes)
 *
 * Sourced from: https://github.com/Anduin2017/HowToCook
 * Format: Recipe objects with nutrition data
 */

// Import types from parent
import type { Recipe, NutritionInfo } from '../types/index.js';

// Re-export Recipe for external use
export type { Recipe } from '../types/index.js';

// ==================== Recipe Data ====================

export interface RawRecipeData {
  name: string;
  description: string;
  category: string;
  difficulty: 'easy' | 'medium' | 'hard';
  cookingTime: number;
  servings: number;
  ingredients: Array<{ name: string; amount: number; unit: string; notes?: string }>;
  steps: string[];
  tags: string[];
  taste: 'light' | 'savory' | 'spicy' | 'sweet' | 'rich';
  suitableFor: string[];
  contraindications: string[];
}

// ==================== Nutrition Calculator ====================

function calculateNutrition(
  ingredients: Array<{ name: string; amount: number; unit: string }>
): NutritionInfo {
  // Simplified nutrition calculation based on ingredients
  const nutritionMap: Record<string, Partial<NutritionInfo>> = {
    // Proteins
    '猪肉': { calories: 143, protein: 21, fat: 6, carbohydrates: 0 },
    '牛肉': { calories: 125, protein: 26, fat: 2, carbohydrates: 0 },
    '鸡肉': { calories: 165, protein: 31, fat: 4, carbohydrates: 0 },
    '鸡胸肉': { calories: 165, protein: 31, fat: 4, carbohydrates: 0 },
    '鸡蛋': { calories: 155, protein: 13, fat: 11, carbohydrates: 1 },
    '虾': { calories: 99, protein: 24, fat: 0, carbohydrates: 0 },
    '鲈鱼': { calories: 105, protein: 18, fat: 3, carbohydrates: 0 },
    '三文鱼': { calories: 208, protein: 20, fat: 13, carbohydrates: 0 },
    '豆腐': { calories: 76, protein: 8, fat: 4, carbohydrates: 2 },
    // Vegetables
    '西兰花': { calories: 34, protein: 3, fat: 0, carbohydrates: 7 },
    '菠菜': { calories: 23, protein: 3, fat: 0, carbohydrates: 4 },
    '胡萝卜': { calories: 41, protein: 1, fat: 0, carbohydrates: 10 },
    '黄瓜': { calories: 15, protein: 1, fat: 0, carbohydrates: 4 },
    '番茄': { calories: 18, protein: 1, fat: 0, carbohydrates: 4 },
    '土豆': { calories: 77, protein: 2, fat: 0, carbohydrates: 17 },
    '茄子': { calories: 25, protein: 1, fat: 0, carbohydrates: 6 },
    '白菜': { calories: 17, protein: 1, fat: 0, carbohydrates: 4 },
    '芹菜': { calories: 16, protein: 1, fat: 0, carbohydrates: 3 },
    '木耳': { calories: 27, protein: 1, fat: 0, carbohydrates: 6 },
    '香菇': { calories: 26, protein: 3, fat: 0, carbohydrates: 4 },
    // Carbs
    '米饭': { calories: 130, protein: 3, fat: 0, carbohydrates: 28 },
    '面条': { calories: 138, protein: 5, fat: 1, carbohydrates: 25 },
    '馒头': { calories: 223, protein: 7, fat: 1, carbohydrates: 45 },
    '面粉': { calories: 364, protein: 10, fat: 1, carbohydrates: 76 },
    '燕麦': { calories: 389, protein: 17, fat: 7, carbohydrates: 66 },
    // Others
    '油': { calories: 884, protein: 0, fat: 100, carbohydrates: 0 },
    '盐': { calories: 0, protein: 0, fat: 0, carbohydrates: 0 },
    '酱油': { calories: 53, protein: 8, fat: 0, carbohydrates: 5 },
    '醋': { calories: 6, protein: 0, fat: 0, carbohydrates: 1 },
    '糖': { calories: 387, protein: 0, fat: 0, carbohydrates: 100 },
    '蒜': { calories: 149, protein: 6, fat: 0, carbohydrates: 33 },
    '姜': { calories: 41, protein: 2, fat: 0, carbohydrates: 10 },
    '葱': { calories: 30, protein: 2, fat: 0, carbohydrates: 7 },
  };

  let total: NutritionInfo = {
    calories: 0, protein: 0, carbohydrates: 0, fat: 0,
    fiber: 0, sugar: 0, sodium: 400, saturatedFat: 0, cholesterol: 0,
    vitamins: { vitaminA: 0, vitaminC: 0, vitaminD: 0, vitaminE: 0, vitaminK: 0, vitaminB12: 0, folate: 0 },
    minerals: { calcium: 0, iron: 0, magnesium: 0, potassium: 0, zinc: 0 },
  };

  for (const ing of ingredients) {
    const key = Object.keys(nutritionMap).find(k => ing.name.includes(k));
    if (key) {
      const n = nutritionMap[key]!;
      const multiplier = ing.amount / 100; // Normalize to 100g
      total.calories += (n.calories || 0) * multiplier;
      total.protein += (n.protein || 0) * multiplier;
      total.fat += (n.fat || 0) * multiplier;
      total.carbohydrates += (n.carbohydrates || 0) * multiplier;
    }
  }

  // Add cooking oil (approximately 15g per dish)
  total.fat += 15;
  total.calories += 132;

  // Round values
  return {
    calories: Math.round(total.calories),
    protein: Math.round(total.protein),
    carbohydrates: Math.round(total.carbohydrates),
    fat: Math.round(total.fat),
    fiber: Math.round(total.carbohydrates * 0.1),
    sugar: Math.round(total.carbohydrates * 0.2),
    sodium: 500,
    saturatedFat: Math.round(total.fat * 0.2),
    cholesterol: total.protein > 10 ? 50 : 0,
    vitamins: {
      vitaminA: Math.round(total.protein * 3),
      vitaminC: Math.round(total.carbohydrates * 2),
      vitaminD: total.protein > 15 ? 5 : 0,
      vitaminE: Math.round(total.fat * 0.1),
      vitaminK: 30,
      vitaminB12: total.protein > 20 ? 2 : 0,
      folate: 40,
    },
    minerals: {
      calcium: Math.round(total.protein * 5),
      iron: Math.round(total.carbohydrates * 0.1),
      magnesium: Math.round(total.protein * 2),
      potassium: Math.round(total.carbohydrates * 5),
      zinc: Math.round(total.protein * 0.2),
    },
  };
}

// ==================== Complete Recipe Database ====================

const RECIPE_DATABASE: RawRecipeData[] = [
  // ========== 早餐 (Breakfast) ==========
  {
    name: '煮鸡蛋',
    description: '最简单的早餐鸡蛋做法',
    category: '早餐',
    difficulty: 'easy',
    cookingTime: 10,
    servings: 1,
    ingredients: [
      { name: '鸡蛋', amount: 2, unit: '个' },
    ],
    steps: ['水开后放入鸡蛋，煮8-10分钟'],
    tags: ['早餐', '高蛋白', '简单'],
    taste: 'light',
    suitableFor: ['all'],
    contraindications: [],
  },
  {
    name: '蒸蛋羹',
    description: '嫩滑的蒸鸡蛋羹',
    category: '早餐',
    difficulty: 'easy',
    cookingTime: 15,
    servings: 2,
    ingredients: [
      { name: '鸡蛋', amount: 2, unit: '个' },
      { name: '盐', amount: 2, unit: 'g' },
      { name: '葱', amount: 5, unit: 'g' },
    ],
    steps: ['鸡蛋打散加水盐调味', '水开后放入蒸8-10分钟', '撒上葱花'],
    tags: ['早餐', '高蛋白', '嫩滑'],
    taste: 'light',
    suitableFor: ['all'],
    contraindications: [],
  },
  {
    name: '燕麦粥',
    description: '营养健康的燕麦早餐',
    category: '早餐',
    difficulty: 'easy',
    cookingTime: 10,
    servings: 1,
    ingredients: [
      { name: '燕麦', amount: 40, unit: 'g' },
      { name: '牛奶', amount: 200, unit: 'ml' },
      { name: '蜂蜜', amount: 10, unit: 'g' },
    ],
    steps: ['牛奶加热至微开', '加入燕麦煮5分钟', '加入蜂蜜调味'],
    tags: ['早餐', '高纤维', '健康'],
    taste: 'sweet',
    suitableFor: ['all'],
    contraindications: [],
  },
  {
    name: '三明治',
    description: '简单美味的三明治',
    category: '早餐',
    difficulty: 'easy',
    cookingTime: 10,
    servings: 1,
    ingredients: [
      { name: '面包', amount: 2, unit: '片' },
      { name: '鸡蛋', amount: 1, unit: '个' },
      { name: '生菜', amount: 30, unit: 'g' },
      { name: '番茄', amount: 50, unit: 'g' },
    ],
    steps: ['鸡蛋煎熟', '面包烤至微黄', '依次放入生菜、番茄、鸡蛋'],
    tags: ['早餐', '快捷'],
    taste: 'savory',
    suitableFor: ['all'],
    contraindications: [],
  },
  {
    name: '豆浆',
    description: '自制香浓豆浆',
    category: '早餐',
    difficulty: 'medium',
    cookingTime: 30,
    servings: 2,
    ingredients: [
      { name: '黄豆', amount: 80, unit: 'g' },
      { name: '水', amount: 800, unit: 'ml' },
      { name: '糖', amount: 20, unit: 'g' },
    ],
    steps: ['黄豆提前浸泡4小时', '加水用豆浆机打碎', '煮沸后加糖调味'],
    tags: ['早餐', '植物蛋白'],
    taste: 'sweet',
    suitableFor: ['all'],
    contraindications: ['soy'],
  },
  {
    name: '油条',
    description: '酥脆的传统油条',
    category: '早餐',
    difficulty: 'hard',
    cookingTime: 20,
    servings: 4,
    ingredients: [
      { name: '面粉', amount: 300, unit: 'g' },
      { name: '油', amount: 500, unit: 'ml' },
      { name: '盐', amount: 3, unit: 'g' },
      { name: '酵母', amount: 3, unit: 'g' },
    ],
    steps: ['面粉加盐酵母水和面', '发酵1小时', '切条油炸至金黄'],
    tags: ['早餐', '传统', '油炸'],
    taste: 'savory',
    suitableFor: ['none'],
    contraindications: ['digestive_health', 'obesity'],
  },
  {
    name: '小米粥',
    description: '养胃的小米粥',
    category: '早餐',
    difficulty: 'easy',
    cookingTime: 30,
    servings: 2,
    ingredients: [
      { name: '小米', amount: 80, unit: 'g' },
      { name: '水', amount: 1000, unit: 'ml' },
    ],
    steps: ['小米洗净加水', '大火烧开后转小火', '煮30分钟至粘稠'],
    tags: ['早餐', '养胃', '易消化'],
    taste: 'light',
    suitableFor: ['all', 'digestive_health'],
    contraindications: [],
  },
  {
    name: '煎饼果子',
    description: '天津特色早餐',
    category: '早餐',
    difficulty: 'medium',
    cookingTime: 15,
    servings: 1,
    ingredients: [
      { name: '面粉', amount: 50, unit: 'g' },
      { name: '鸡蛋', amount: 1, unit: '个' },
      { name: '油条', amount: 1, unit: '根' },
      { name: '葱', amount: 10, unit: 'g' },
    ],
    steps: ['面粉加水调成糊', '平底锅摊成薄饼', '打上鸡蛋撒葱花', '卷入油条'],
    tags: ['早餐', '传统', '特色'],
    taste: 'savory',
    suitableFor: ['none'],
    contraindications: ['digestive_health', 'obesity'],
  },

  // ========== 主食 (Main Courses) ==========
  {
    name: '蛋炒饭',
    description: '经典的中式蛋炒饭',
    category: '主食',
    difficulty: 'easy',
    cookingTime: 10,
    servings: 1,
    ingredients: [
      { name: '米饭', amount: 200, unit: 'g' },
      { name: '鸡蛋', amount: 2, unit: '个' },
      { name: '葱', amount: 20, unit: 'g' },
      { name: '盐', amount: 3, unit: 'g' },
      { name: '油', amount: 15, unit: 'ml' },
    ],
    steps: ['鸡蛋打散，米饭弄散', '热锅下油炒蛋液', '加入米饭翻炒', '加盐调味撒葱花'],
    tags: ['主食', '快捷', '经典'],
    taste: 'savory',
    suitableFor: ['all'],
    contraindications: ['egg'],
  },
  {
    name: '番茄炒蛋',
    description: '国民家常菜',
    category: '主食',
    difficulty: 'easy',
    cookingTime: 10,
    servings: 2,
    ingredients: [
      { name: '番茄', amount: 200, unit: 'g' },
      { name: '鸡蛋', amount: 3, unit: '个' },
      { name: '葱', amount: 20, unit: 'g' },
      { name: '盐', amount: 3, unit: 'g' },
      { name: '糖', amount: 5, unit: 'g' },
    ],
    steps: ['番茄切块，鸡蛋打散', '先炒鸡蛋盛出', '再炒番茄加糖', '混合炒匀加盐'],
    tags: ['主食', '家常', '下饭'],
    taste: 'savory',
    suitableFor: ['all'],
    contraindications: ['egg'],
  },
  {
    name: '红烧肉',
    description: '肥而不腻的红烧肉',
    category: '主食',
    difficulty: 'medium',
    cookingTime: 60,
    servings: 4,
    ingredients: [
      { name: '五花肉', amount: 500, unit: 'g' },
      { name: '酱油', amount: 30, unit: 'ml' },
      { name: '糖', amount: 30, unit: 'g' },
      { name: '姜', amount: 20, unit: 'g' },
      { name: '葱', amount: 30, unit: 'g' },
    ],
    steps: ['五花肉切块焯水', '炒糖色放入肉块', '加酱油姜葱加水', '小火炖60分钟'],
    tags: ['主食', '硬菜', '下饭'],
    taste: 'rich',
    suitableFor: ['none'],
    contraindications: ['hypertension', 'hyperlipidemia', 'obesity'],
  },
  {
    name: '宫保鸡丁',
    description: '四川名菜',
    category: '主食',
    difficulty: 'medium',
    cookingTime: 20,
    servings: 2,
    ingredients: [
      { name: '鸡胸肉', amount: 200, unit: 'g' },
      { name: '花生', amount: 50, unit: 'g' },
      { name: '干辣椒', amount: 10, unit: 'g' },
      { name: '花椒', amount: 5, unit: 'g' },
      { name: '葱', amount: 30, unit: 'g' },
    ],
    steps: ['鸡肉切丁腌制', '热锅炒鸡肉丁', '加入辣椒花椒', '加入花生翻炒'],
    tags: ['主食', '川菜', '辣'],
    taste: 'spicy',
    suitableFor: ['none'],
    contraindications: ['gastritis'],
  },
  {
    name: '糖醋里脊',
    description: '酸甜可口的里脊肉',
    category: '主食',
    difficulty: 'medium',
    cookingTime: 20,
    servings: 2,
    ingredients: [
      { name: '猪里脊', amount: 200, unit: 'g' },
      { name: '番茄酱', amount: 30, unit: 'g' },
      { name: '糖', amount: 30, unit: 'g' },
      { name: '醋', amount: 20, unit: 'ml' },
      { name: '面粉', amount: 50, unit: 'g' },
    ],
    steps: ['里脊切条裹面粉', '油炸至金黄', '糖醋汁加热', '里脊裹汁'],
    tags: ['主食', '酸甜', '下饭'],
    taste: 'sweet',
    suitableFor: ['none'],
    contraindications: ['hyperlipidemia', 'obesity'],
  },
  {
    name: '麻婆豆腐',
    description: '麻辣鲜香的川菜',
    category: '主食',
    difficulty: 'medium',
    cookingTime: 15,
    servings: 2,
    ingredients: [
      { name: '豆腐', amount: 300, unit: 'g' },
      { name: '猪肉末', amount: 50, unit: 'g' },
      { name: '郫县豆瓣酱', amount: 20, unit: 'g' },
      { name: '花椒', amount: 5, unit: 'g' },
      { name: '葱', amount: 20, unit: 'g' },
    ],
    steps: ['豆腐切块焯水', '炒肉末加豆瓣酱', '加水煮豆腐', '勾芡撒花椒葱花'],
    tags: ['主食', '川菜', '麻辣'],
    taste: 'spicy',
    suitableFor: ['none'],
    contraindications: ['gastritis', 'renal_disease'],
  },
  {
    name: '回锅肉',
    description: '四川传统名菜',
    category: '主食',
    difficulty: 'medium',
    cookingTime: 30,
    servings: 2,
    ingredients: [
      { name: '五花肉', amount: 300, unit: 'g' },
      { name: '青蒜', amount: 100, unit: 'g' },
      { name: '郫县豆瓣酱', amount: 20, unit: 'g' },
      { name: '甜面酱', amount: 10, unit: 'g' },
    ],
    steps: ['五花肉煮至七成熟', '切片煸炒出油', '加豆瓣酱甜面酱', '加入青蒜翻炒'],
    tags: ['主食', '川菜', '下饭'],
    taste: 'savory',
    suitableFor: ['none'],
    contraindications: ['hypertension', 'hyperlipidemia', 'obesity'],
  },
  {
    name: '鱼香肉丝',
    description: '酸甜微辣的川菜',
    category: '主食',
    difficulty: 'medium',
    cookingTime: 20,
    servings: 2,
    ingredients: [
      { name: '猪肉', amount: 200, unit: 'g' },
      { name: '木耳', amount: 50, unit: 'g' },
      { name: '胡萝卜', amount: 50, unit: 'g' },
      { name: '泡椒', amount: 20, unit: 'g' },
      { name: '葱姜蒜', amount: 30, unit: 'g' },
    ],
    steps: ['肉丝腌制', '木耳胡萝卜切丝', '炒肉丝加泡椒', '加入配菜调味'],
    tags: ['主食', '川菜', '下饭'],
    taste: 'spicy',
    suitableFor: ['none'],
    contraindications: [],
  },
  {
    name: '红烧排骨',
    description: '酱香浓郁的红烧排骨',
    category: '主食',
    difficulty: 'medium',
    cookingTime: 45,
    servings: 3,
    ingredients: [
      { name: '排骨', amount: 500, unit: 'g' },
      { name: '酱油', amount: 30, unit: 'ml' },
      { name: '糖', amount: 20, unit: 'g' },
      { name: '姜', amount: 20, unit: 'g' },
      { name: '葱', amount: 30, unit: 'g' },
    ],
    steps: ['排骨焯水', '炒糖色放排骨', '加酱油姜葱', '加水炖40分钟'],
    tags: ['主食', '硬菜', '高蛋白'],
    taste: 'rich',
    suitableFor: ['none'],
    contraindications: ['hyperlipidemia', 'obesity'],
  },
  {
    name: '可乐鸡翅',
    description: '甜香可口的鸡翅',
    category: '主食',
    difficulty: 'easy',
    cookingTime: 25,
    servings: 2,
    ingredients: [
      { name: '鸡翅中', amount: 300, unit: 'g' },
      { name: '可乐', amount: 200, unit: 'ml' },
      { name: '酱油', amount: 20, unit: 'ml' },
      { name: '姜', amount: 15, unit: 'g' },
    ],
    steps: ['鸡翅焯水', '热锅下鸡翅', '加可乐酱油', '炖煮20分钟'],
    tags: ['主食', '简单', '甜口'],
    taste: 'sweet',
    suitableFor: ['none'],
    contraindications: ['diabetes'],
  },
  {
    name: '土豆炖牛肉',
    description: '营养丰富的炖菜',
    category: '主食',
    difficulty: 'medium',
    cookingTime: 90,
    servings: 4,
    ingredients: [
      { name: '牛肉', amount: 400, unit: 'g' },
      { name: '土豆', amount: 300, unit: 'g' },
      { name: '胡萝卜', amount: 100, unit: 'g' },
      { name: '洋葱', amount: 100, unit: 'g' },
      { name: '番茄酱', amount: 30, unit: 'g' },
    ],
    steps: ['牛肉切块焯水', '炒香洋葱番茄酱', '加入牛肉翻炒', '加水炖90分钟'],
    tags: ['主食', '炖菜', '高蛋白'],
    taste: 'savory',
    suitableFor: ['all'],
    contraindications: [],
  },
  {
    name: '蒜蓉虾',
    description: '蒜香浓郁的虾',
    category: '主食',
    difficulty: 'easy',
    cookingTime: 15,
    servings: 2,
    ingredients: [
      { name: '虾', amount: 300, unit: 'g' },
      { name: '蒜', amount: 50, unit: 'g' },
      { name: '葱', amount: 30, unit: 'g' },
      { name: '油', amount: 30, unit: 'ml' },
    ],
    steps: ['虾洗净去虾线', '蒜蓉爆香', '下虾翻炒', '撒葱花出锅'],
    tags: ['主食', '海鲜', '高蛋白'],
    taste: 'savory',
    suitableFor: ['all'],
    contraindications: [],
  },
  {
    name: '清蒸螃蟹',
    description: '保留鲜味的蒸螃蟹',
    category: '主食',
    difficulty: 'easy',
    cookingTime: 20,
    servings: 2,
    ingredients: [
      { name: '螃蟹', amount: 2, unit: '只' },
      { name: '姜', amount: 30, unit: 'g' },
      { name: '醋', amount: 30, unit: 'ml' },
    ],
    steps: ['螃蟹洗净', '水开后放入', '蒸15-20分钟', '姜醋蘸料'],
    tags: ['主食', '海鲜', '高端'],
    taste: 'light',
    suitableFor: ['all'],
    contraindications: [],
  },
  {
    name: '水煮鱼',
    description: '麻辣鲜香的水煮鱼',
    category: '主食',
    difficulty: 'hard',
    cookingTime: 30,
    servings: 4,
    ingredients: [
      { name: '草鱼', amount: 500, unit: 'g' },
      { name: '豆芽', amount: 200, unit: 'g' },
      { name: '干辣椒', amount: 30, unit: 'g' },
      { name: '花椒', amount: 15, unit: 'g' },
      { name: '郫县豆瓣酱', amount: 50, unit: 'g' },
    ],
    steps: ['鱼片成片腌制', '炒香豆瓣酱加水', '豆芽焯水垫底', '煮鱼片捞出', '浇热油'],
    tags: ['主食', '川菜', '麻辣'],
    taste: 'spicy',
    suitableFor: ['none'],
    contraindications: ['gastritis', 'renal_disease'],
  },
  {
    name: '京酱肉丝',
    description: '北京传统名菜',
    category: '主食',
    difficulty: 'medium',
    cookingTime: 20,
    servings: 2,
    ingredients: [
      { name: '猪肉里脊', amount: 200, unit: 'g' },
      { name: '豆腐皮', amount: 100, unit: 'g' },
      { name: '大葱', amount: 100, unit: 'g' },
      { name: '甜面酱', amount: 30, unit: 'g' },
    ],
    steps: ['肉丝腌制', '甜面酱炒香', '下肉丝翻炒', '豆腐皮卷葱丝肉丝'],
    tags: ['主食', '京菜', '传统'],
    taste: 'savory',
    suitableFor: ['all'],
    contraindications: [],
  },
  {
    name: '锅包肉',
    description: '东北名菜',
    category: '主食',
    difficulty: 'hard',
    cookingTime: 25,
    servings: 2,
    ingredients: [
      { name: '猪里脊', amount: 200, unit: 'g' },
      { name: '淀粉', amount: 100, unit: 'g' },
      { name: '糖', amount: 30, unit: 'g' },
      { name: '醋', amount: 20, unit: 'ml' },
      { name: '葱姜蒜', amount: 30, unit: 'g' },
    ],
    steps: ['肉片裹淀粉糊', '油炸至酥脆', '糖醋汁加热', '肉片裹汁'],
    tags: ['主食', '东北菜', '酸甜'],
    taste: 'sweet',
    suitableFor: ['none'],
    contraindications: ['hyperlipidemia', 'obesity'],
  },
  {
    name: '地三鲜',
    description: '东北经典素菜',
    category: '主食',
    difficulty: 'easy',
    cookingTime: 20,
    servings: 2,
    ingredients: [
      { name: '土豆', amount: 200, unit: 'g' },
      { name: '茄子', amount: 200, unit: 'g' },
      { name: '青椒', amount: 100, unit: 'g' },
      { name: '蒜', amount: 30, unit: 'g' },
      { name: '酱油', amount: 20, unit: 'ml' },
    ],
    steps: ['土豆茄子青椒切块', '分别油炸', '蒜末爆香', '混合翻炒调味'],
    tags: ['主食', '东北菜', '素菜'],
    taste: 'savory',
    suitableFor: ['all'],
    contraindications: [],
  },
  {
    name: '糖醋排骨',
    description: '酸甜可口的排骨',
    category: '主食',
    difficulty: 'medium',
    cookingTime: 40,
    servings: 2,
    ingredients: [
      { name: '排骨', amount: 400, unit: 'g' },
      { name: '糖', amount: 40, unit: 'g' },
      { name: '醋', amount: 30, unit: 'ml' },
      { name: '酱油', amount: 20, unit: 'ml' },
      { name: '姜', amount: 15, unit: 'g' },
    ],
    steps: ['排骨焯水', '炒糖色', '加醋酱油姜', '加水炖30分钟', '收汁'],
    tags: ['主食', '酸甜', '下饭'],
    taste: 'sweet',
    suitableFor: ['none'],
    contraindications: ['diabetes', 'hyperlipidemia'],
  },
  {
    name: '蚝油生菜',
    description: '清爽的蚝油生菜',
    category: '主食',
    difficulty: 'easy',
    cookingTime: 5,
    servings: 2,
    ingredients: [
      { name: '生菜', amount: 300, unit: 'g' },
      { name: '蚝油', amount: 30, unit: 'ml' },
      { name: '蒜', amount: 20, unit: 'g' },
      { name: '油', amount: 15, unit: 'ml' },
    ],
    steps: ['生菜洗净焯水', '蒜末爆香', '加蚝油和水', '淋在生菜上'],
    tags: ['主食', '素菜', '简单'],
    taste: 'savory',
    suitableFor: ['all'],
    contraindications: [],
  },
  {
    name: '干煸四季豆',
    description: '香辣下饭的四季豆',
    category: '主食',
    difficulty: 'easy',
    cookingTime: 15,
    servings: 2,
    ingredients: [
      { name: '四季豆', amount: 300, unit: 'g' },
      { name: '干辣椒', amount: 15, unit: 'g' },
      { name: '花椒', amount: 5, unit: 'g' },
      { name: '蒜', amount: 20, unit: 'g' },
      { name: '肉末', amount: 50, unit: 'g' },
    ],
    steps: ['四季豆掐段', '干煸至起皱', '爆香辣椒花椒蒜', '加入肉末翻炒'],
    tags: ['主食', '素菜', '下饭'],
    taste: 'spicy',
    suitableFor: ['all'],
    contraindications: [],
  },

  // ========== 汤类 (Soups) ==========
  {
    name: '番茄鸡蛋汤',
    description: '酸甜开胃的汤',
    category: '汤',
    difficulty: 'easy',
    cookingTime: 15,
    servings: 4,
    ingredients: [
      { name: '番茄', amount: 200, unit: 'g' },
      { name: '鸡蛋', amount: 2, unit: '个' },
      { name: '葱', amount: 20, unit: 'g' },
      { name: '盐', amount: 5, unit: 'g' },
    ],
    steps: ['番茄切块', '加水煮沸', '加入蛋液', '加盐撒葱'],
    tags: ['汤', '家常', '开胃'],
    taste: 'light',
    suitableFor: ['all'],
    contraindications: ['egg'],
  },
  {
    name: '紫菜蛋花汤',
    description: '清淡鲜美的汤',
    category: '汤',
    difficulty: 'easy',
    cookingTime: 10,
    servings: 4,
    ingredients: [
      { name: '紫菜', amount: 20, unit: 'g' },
      { name: '鸡蛋', amount: 1, unit: '个' },
      { name: '葱', amount: 15, unit: 'g' },
      { name: '盐', amount: 3, unit: 'g' },
    ],
    steps: ['紫菜泡发', '加水煮沸', '加入蛋液', '加盐撒葱'],
    tags: ['汤', '清淡', '简单'],
    taste: 'light',
    suitableFor: ['all'],
    contraindications: ['egg'],
  },
  {
    name: '排骨玉米汤',
    description: '营养滋补的汤',
    category: '汤',
    difficulty: 'easy',
    cookingTime: 60,
    servings: 6,
    ingredients: [
      { name: '排骨', amount: 400, unit: 'g' },
      { name: '玉米', amount: 2, unit: '根' },
      { name: '胡萝卜', amount: 100, unit: 'g' },
      { name: '姜', amount: 20, unit: 'g' },
    ],
    steps: ['排骨焯水', '玉米胡萝卜切块', '加水大火烧开', '小火炖60分钟'],
    tags: ['汤', '滋补', '营养'],
    taste: 'light',
    suitableFor: ['all'],
    contraindications: [],
  },
  {
    name: '鸡汤',
    description: '滋补养颜的鸡汤',
    category: '汤',
    difficulty: 'easy',
    cookingTime: 90,
    servings: 6,
    ingredients: [
      { name: '整鸡', amount: 1000, unit: 'g' },
      { name: '姜', amount: 30, unit: 'g' },
      { name: '葱', amount: 30, unit: 'g' },
      { name: '枸杞', amount: 10, unit: 'g' },
    ],
    steps: ['鸡洗净焯水', '加水加姜葱', '大火烧开撇沫', '小火炖90分钟', '加枸杞'],
    tags: ['汤', '滋补', '养颜'],
    taste: 'light',
    suitableFor: ['all'],
    contraindications: [],
  },
  {
    name: '酸辣汤',
    description: '开胃的酸辣汤',
    category: '汤',
    difficulty: 'easy',
    cookingTime: 15,
    servings: 4,
    ingredients: [
      { name: '豆腐', amount: 100, unit: 'g' },
      { name: '木耳', amount: 30, unit: 'g' },
      { name: '胡萝卜', amount: 50, unit: 'g' },
      { name: '醋', amount: 30, unit: 'ml' },
      { name: '辣椒油', amount: 10, unit: 'ml' },
    ],
    steps: ['配料切丝', '加水煮沸', '加入配料', '加醋胡椒', '勾芡'],
    tags: ['汤', '酸辣', '开胃'],
    taste: 'spicy',
    suitableFor: ['none'],
    contraindications: ['gastritis'],
  },
  {
    name: '冬瓜排骨汤',
    description: '清热解暑的汤',
    category: '汤',
    difficulty: 'easy',
    cookingTime: 60,
    servings: 6,
    ingredients: [
      { name: '排骨', amount: 400, unit: 'g' },
      { name: '冬瓜', amount: 500, unit: 'g' },
      { name: '姜', amount: 20, unit: 'g' },
      { name: '葱', amount: 20, unit: 'g' },
    ],
    steps: ['排骨焯水', '冬瓜切块', '加水煮沸', '小火炖50分钟', '加冬瓜再煮10分钟'],
    tags: ['汤', '清热', '夏季'],
    taste: 'light',
    suitableFor: ['all', 'weight_loss'],
    contraindications: [],
  },
  {
    name: '鱼头豆腐汤',
    description: '营养丰富的鱼头汤',
    category: '汤',
    difficulty: 'medium',
    cookingTime: 30,
    servings: 4,
    ingredients: [
      { name: '鱼头', amount: 500, unit: 'g' },
      { name: '豆腐', amount: 200, unit: 'g' },
      { name: '姜', amount: 30, unit: 'g' },
      { name: '葱', amount: 20, unit: 'g' },
    ],
    steps: ['鱼头煎至金黄', '加姜和水煮沸', '加入豆腐', '煮20分钟撒葱'],
    tags: ['汤', '高蛋白', '营养'],
    taste: 'light',
    suitableFor: ['all'],
    contraindications: [],
  },
  {
    name: '莲藕排骨汤',
    description: '润肺养胃的汤',
    category: '汤',
    difficulty: 'easy',
    cookingTime: 90,
    servings: 6,
    ingredients: [
      { name: '排骨', amount: 400, unit: 'g' },
      { name: '莲藕', amount: 300, unit: 'g' },
      { name: '花生', amount: 100, unit: 'g' },
      { name: '姜', amount: 20, unit: 'g' },
    ],
    steps: ['排骨焯水', '莲藕花生切块', '加水大火烧开', '小火炖90分钟'],
    tags: ['汤', '润肺', '养胃'],
    taste: 'light',
    suitableFor: ['all'],
    contraindications: [],
  },

  // ========== 凉菜 (Cold Dishes) ==========
  {
    name: '凉拌黄瓜',
    description: '清爽的凉拌黄瓜',
    category: '凉菜',
    difficulty: 'easy',
    cookingTime: 10,
    servings: 2,
    ingredients: [
      { name: '黄瓜', amount: 300, unit: 'g' },
      { name: '蒜', amount: 15, unit: 'g' },
      { name: '醋', amount: 15, unit: 'ml' },
      { name: '盐', amount: 3, unit: 'g' },
      { name: '香油', amount: 10, unit: 'ml' },
    ],
    steps: ['黄瓜拍碎切段', '蒜泥加醋盐香油', '拌匀即可'],
    tags: ['凉菜', '清爽', '夏季'],
    taste: 'light',
    suitableFor: ['all', 'weight_loss'],
    contraindications: [],
  },
  {
    name: '凉拌木耳',
    description: '清爽的木耳凉拌菜',
    category: '凉菜',
    difficulty: 'easy',
    cookingTime: 15,
    servings: 2,
    ingredients: [
      { name: '黑木耳', amount: 50, unit: 'g' },
      { name: '黄瓜', amount: 100, unit: 'g' },
      { name: '蒜', amount: 10, unit: 'g' },
      { name: '醋', amount: 15, unit: 'ml' },
      { name: '香油', amount: 10, unit: 'ml' },
    ],
    steps: ['木耳泡发焯水', '黄瓜切丝', '蒜泥加调料', '拌匀即可'],
    tags: ['凉菜', '护肝', '高纤维'],
    taste: 'light',
    suitableFor: ['all', 'digestive_health'],
    contraindications: [],
  },
  {
    name: '皮蛋豆腐',
    description: '经典凉菜',
    category: '凉菜',
    difficulty: 'easy',
    cookingTime: 5,
    servings: 2,
    ingredients: [
      { name: '皮蛋', amount: 2, unit: '个' },
      { name: '豆腐', amount: 200, unit: 'g' },
      { name: '酱油', amount: 15, unit: 'ml' },
      { name: '葱', amount: 15, unit: 'g' },
      { name: '香油', amount: 10, unit: 'ml' },
    ],
    steps: ['豆腐切块', '皮蛋切块', '摆盘淋酱油香油', '撒葱花'],
    tags: ['凉菜', '经典', '简单'],
    taste: 'savory',
    suitableFor: ['all'],
    contraindications: ['egg'],
  },
  {
    name: '凉拌海带丝',
    description: '清爽的海带丝',
    category: '凉菜',
    difficulty: 'easy',
    cookingTime: 10,
    servings: 2,
    ingredients: [
      { name: '海带', amount: 100, unit: 'g' },
      { name: '胡萝卜', amount: 50, unit: 'g' },
      { name: '蒜', amount: 15, unit: 'g' },
      { name: '醋', amount: 15, unit: 'ml' },
      { name: '香油', amount: 10, unit: 'ml' },
    ],
    steps: ['海带泡发切丝', '胡萝卜切丝焯水', '蒜泥加调料', '拌匀即可'],
    tags: ['凉菜', '高碘', '清爽'],
    taste: 'light',
    suitableFor: ['all'],
    contraindications: [],
  },
  {
    name: '蒜泥白肉',
    description: '四川传统凉菜',
    category: '凉菜',
    difficulty: 'medium',
    cookingTime: 30,
    servings: 4,
    ingredients: [
      { name: '五花肉', amount: 400, unit: 'g' },
      { name: '蒜', amount: 50, unit: 'g' },
      { name: '酱油', amount: 30, unit: 'ml' },
      { name: '醋', amount: 15, unit: 'ml' },
      { name: '红油', amount: 20, unit: 'ml' },
    ],
    steps: ['五花肉煮至七成熟', '冰镇后切片', '蒜泥加调料', '肉片蘸料食用'],
    tags: ['凉菜', '川菜', '经典'],
    taste: 'savory',
    suitableFor: ['none'],
    contraindications: ['hypertension', 'hyperlipidemia'],
  },
  {
    name: '夫妻肺片',
    description: '四川经典凉菜',
    category: '凉菜',
    difficulty: 'medium',
    cookingTime: 30,
    servings: 2,
    ingredients: [
      { name: '牛杂', amount: 200, unit: 'g' },
      { name: '牛肚', amount: 100, unit: 'g' },
      { name: '红油', amount: 30, unit: 'ml' },
      { name: '花生碎', amount: 30, unit: 'g' },
      { name: '芹菜', amount: 50, unit: 'g' },
    ],
    steps: ['牛杂牛肚卤熟', '切片摆盘', '红油花生碎淋面', '加芹菜点缀'],
    tags: ['凉菜', '川菜', '经典'],
    taste: 'spicy',
    suitableFor: ['none'],
    contraindications: ['hyperlipidemia'],
  },
  {
    name: '老醋花生',
    description: '酸香的下酒菜',
    category: '凉菜',
    difficulty: 'easy',
    cookingTime: 10,
    servings: 2,
    ingredients: [
      { name: '花生', amount: 100, unit: 'g' },
      { name: '醋', amount: 30, unit: 'ml' },
      { name: '糖', amount: 15, unit: 'g' },
      { name: '洋葱', amount: 50, unit: 'g' },
      { name: '青椒', amount: 50, unit: 'g' },
    ],
    steps: ['花生米炸熟', '醋糖调成汁', '洋葱青椒切丁', '拌匀即可'],
    tags: ['凉菜', '下酒', '简单'],
    taste: 'savory',
    suitableFor: ['all'],
    contraindications: [],
  },
  {
    name: '蓝莓山药',
    description: '甜品凉菜',
    category: '凉菜',
    difficulty: 'easy',
    cookingTime: 20,
    servings: 2,
    ingredients: [
      { name: '山药', amount: 300, unit: 'g' },
      { name: '蓝莓酱', amount: 50, unit: 'g' },
      { name: '蜂蜜', amount: 20, unit: 'g' },
    ],
    steps: ['山药去皮切段', '蒸熟压成泥', '摆成形状', '淋蓝莓酱蜂蜜'],
    tags: ['凉菜', '甜品', '养胃'],
    taste: 'sweet',
    suitableFor: ['all'],
    contraindications: [],
  },

  // ========== 素菜 (Vegetable Dishes) ==========
  {
    name: '蒜蓉西兰花',
    description: '营养丰富的家常蔬菜',
    category: '素菜',
    difficulty: 'easy',
    cookingTime: 10,
    servings: 2,
    ingredients: [
      { name: '西兰花', amount: 300, unit: 'g' },
      { name: '蒜', amount: 20, unit: 'g' },
      { name: '盐', amount: 3, unit: 'g' },
      { name: '油', amount: 15, unit: 'ml' },
    ],
    steps: ['西兰花掰小块', '焯水30秒', '蒜末爆香', '翻炒加盐'],
    tags: ['素菜', '高纤维', '抗癌'],
    taste: 'savory',
    suitableFor: ['all', 'weight_loss'],
    contraindications: [],
  },
  {
    name: '蚝油香菇',
    description: '鲜美的香菇菜',
    category: '素菜',
    difficulty: 'easy',
    cookingTime: 15,
    servings: 2,
    ingredients: [
      { name: '香菇', amount: 200, unit: 'g' },
      { name: '蚝油', amount: 30, unit: 'ml' },
      { name: '青椒', amount: 50, unit: 'g' },
      { name: '蒜', amount: 15, unit: 'g' },
    ],
    steps: ['香菇切片焯水', '蒜末爆香', '加蚝油翻炒', '加青椒调味'],
    tags: ['素菜', '鲜香', '高蛋白'],
    taste: 'savory',
    suitableFor: ['all'],
    contraindications: [],
  },
  {
    name: '干锅菜花',
    description: '香辣下饭的菜花',
    category: '素菜',
    difficulty: 'easy',
    cookingTime: 15,
    servings: 2,
    ingredients: [
      { name: '菜花', amount: 300, unit: 'g' },
      { name: '干辣椒', amount: 10, unit: 'g' },
      { name: '蒜', amount: 20, unit: 'g' },
      { name: '五花肉', amount: 50, unit: 'g' },
    ],
    steps: ['菜花掰小块', '五花肉煸油', '爆香辣椒蒜', '加入菜花翻炒'],
    tags: ['素菜', '辣', '下饭'],
    taste: 'spicy',
    suitableFor: ['all'],
    contraindications: [],
  },
  {
    name: '地三鲜',
    description: '东北经典素菜',
    category: '素菜',
    difficulty: 'medium',
    cookingTime: 20,
    servings: 2,
    ingredients: [
      { name: '土豆', amount: 200, unit: 'g' },
      { name: '茄子', amount: 200, unit: 'g' },
      { name: '青椒', amount: 100, unit: 'g' },
      { name: '蒜', amount: 30, unit: 'g' },
      { name: '酱油', amount: 20, unit: 'ml' },
    ],
    steps: ['土豆茄子青椒切块', '分别油炸', '蒜末爆香', '混合翻炒调味'],
    tags: ['素菜', '东北菜', '经典'],
    taste: 'savory',
    suitableFor: ['all'],
    contraindications: [],
  },
  {
    name: '香干炒芹菜',
    description: '清爽的素菜',
    category: '素菜',
    difficulty: 'easy',
    cookingTime: 10,
    servings: 2,
    ingredients: [
      { name: '香干', amount: 150, unit: 'g' },
      { name: '芹菜', amount: 200, unit: 'g' },
      { name: '胡萝卜', amount: 50, unit: 'g' },
      { name: '蒜', amount: 15, unit: 'g' },
    ],
    steps: ['香干切条', '芹菜切段', '蒜末爆香', '依次翻炒加盐'],
    tags: ['素菜', '清爽', '高纤维'],
    taste: 'savory',
    suitableFor: ['all', 'hypertension'],
    contraindications: [],
  },
  {
    name: '炒时蔬',
    description: '简单的时令蔬菜',
    category: '素菜',
    difficulty: 'easy',
    cookingTime: 10,
    servings: 2,
    ingredients: [
      { name: '时令蔬菜', amount: 300, unit: 'g' },
      { name: '蒜', amount: 15, unit: 'g' },
      { name: '盐', amount: 3, unit: 'g' },
      { name: '油', amount: 15, unit: 'ml' },
    ],
    steps: ['蔬菜洗净切段', '蒜末爆香', '大火爆炒', '加盐出锅'],
    tags: ['素菜', '简单', '健康'],
    taste: 'light',
    suitableFor: ['all'],
    contraindications: [],
  },
  {
    name: '蒜蓉炒菜心',
    description: '清爽的广东菜',
    category: '素菜',
    difficulty: 'easy',
    cookingTime: 5,
    servings: 2,
    ingredients: [
      { name: '菜心', amount: 300, unit: 'g' },
      { name: '蒜', amount: 20, unit: 'g' },
      { name: '盐', amount: 3, unit: 'g' },
      { name: '油', amount: 15, unit: 'ml' },
    ],
    steps: ['菜心洗净', '蒜末爆香', '下菜心大火翻炒', '加盐出锅'],
    tags: ['素菜', '粤菜', '清爽'],
    taste: 'light',
    suitableFor: ['all'],
    contraindications: [],
  },
  {
    name: '红烧茄子',
    description: '下饭的红烧茄子',
    category: '素菜',
    difficulty: 'easy',
    cookingTime: 15,
    servings: 2,
    ingredients: [
      { name: '茄子', amount: 300, unit: 'g' },
      { name: '蒜', amount: 30, unit: 'g' },
      { name: '酱油', amount: 20, unit: 'ml' },
      { name: '糖', amount: 10, unit: 'g' },
    ],
    steps: ['茄子切条', '油炸至软', '蒜末爆香', '加酱油糖水炖', '收汁'],
    tags: ['素菜', '下饭', '经典'],
    taste: 'savory',
    suitableFor: ['all'],
    contraindications: [],
  },
  {
    name: '麻婆豆腐',
    description: '麻辣鲜香的豆腐',
    category: '素菜',
    difficulty: 'medium',
    cookingTime: 15,
    servings: 2,
    ingredients: [
      { name: '嫩豆腐', amount: 300, unit: 'g' },
      { name: '猪肉末', amount: 50, unit: 'g' },
      { name: '郫县豆瓣酱', amount: 20, unit: 'g' },
      { name: '花椒粉', amount: 3, unit: 'g' },
      { name: '蒜苗', amount: 50, unit: 'g' },
    ],
    steps: ['豆腐切块焯水', '炒肉末豆瓣酱', '加水煮豆腐', '勾芡撒花椒蒜苗'],
    tags: ['素菜', '川菜', '麻辣'],
    taste: 'spicy',
    suitableFor: ['none'],
    contraindications: ['gastritis', 'renal_disease'],
  },
  {
    name: '清炒苦瓜',
    description: '清热解毒的苦瓜',
    category: '素菜',
    difficulty: 'easy',
    cookingTime: 10,
    servings: 2,
    ingredients: [
      { name: '苦瓜', amount: 250, unit: 'g' },
      { name: '蒜', amount: 15, unit: 'g' },
      { name: '盐', amount: 3, unit: 'g' },
      { name: '鸡蛋', amount: 1, unit: '个' },
    ],
    steps: ['苦瓜切片焯水去苦', '鸡蛋炒熟', '蒜末爆香', '混合翻炒加盐'],
    tags: ['素菜', '清热', '夏季'],
    taste: 'light',
    suitableFor: ['all', 'diabetes'],
    contraindications: [],
  },

  // ========== 荤菜 (Meat Dishes) ==========
  {
    name: '红烧肉',
    description: '肥而不腻的经典红烧肉',
    category: '荤菜',
    difficulty: 'medium',
    cookingTime: 60,
    servings: 4,
    ingredients: [
      { name: '五花肉', amount: 500, unit: 'g' },
      { name: '冰糖', amount: 30, unit: 'g' },
      { name: '酱油', amount: 40, unit: 'ml' },
      { name: '姜', amount: 30, unit: 'g' },
      { name: '葱', amount: 50, unit: 'g' },
    ],
    steps: ['五花肉切块焯水', '炒糖色放入肉块', '加酱油姜葱', '加水小火炖60分钟'],
    tags: ['荤菜', '经典', '下饭'],
    taste: 'rich',
    suitableFor: ['none'],
    contraindications: ['hypertension', 'hyperlipidemia', 'obesity'],
  },
  {
    name: '糖醋里脊',
    description: '酸甜可口的里脊肉',
    category: '荤菜',
    difficulty: 'medium',
    cookingTime: 20,
    servings: 2,
    ingredients: [
      { name: '猪里脊', amount: 200, unit: 'g' },
      { name: '番茄酱', amount: 30, unit: 'g' },
      { name: '糖', amount: 30, unit: 'g' },
      { name: '醋', amount: 20, unit: 'ml' },
      { name: '淀粉', amount: 50, unit: 'g' },
    ],
    steps: ['里脊切条裹淀粉', '油炸至金黄', '糖醋汁加热', '里脊裹汁'],
    tags: ['荤菜', '酸甜', '下饭'],
    taste: 'sweet',
    suitableFor: ['none'],
    contraindications: ['hyperlipidemia', 'obesity'],
  },
  {
    name: '可乐鸡翅',
    description: '甜香可口的鸡翅',
    category: '荤菜',
    difficulty: 'easy',
    cookingTime: 25,
    servings: 3,
    ingredients: [
      { name: '鸡翅中', amount: 400, unit: 'g' },
      { name: '可乐', amount: 330, unit: 'ml' },
      { name: '酱油', amount: 30, unit: 'ml' },
      { name: '姜', amount: 20, unit: 'g' },
    ],
    steps: ['鸡翅焯水', '热锅下鸡翅', '加可乐酱油', '中火炖20分钟'],
    tags: ['荤菜', '简单', '甜口'],
    taste: 'sweet',
    suitableFor: ['none'],
    contraindications: ['diabetes'],
  },
  {
    name: '宫保鸡丁',
    description: '四川名菜',
    category: '荤菜',
    difficulty: 'medium',
    cookingTime: 20,
    servings: 2,
    ingredients: [
      { name: '鸡胸肉', amount: 200, unit: 'g' },
      { name: '花生米', amount: 50, unit: 'g' },
      { name: '干辣椒', amount: 10, unit: 'g' },
      { name: '花椒', amount: 5, unit: 'g' },
      { name: '葱', amount: 30, unit: 'g' },
    ],
    steps: ['鸡肉切丁腌制', '热锅炒鸡肉丁', '加入辣椒花椒', '加入花生翻炒'],
    tags: ['荤菜', '川菜', '辣'],
    taste: 'spicy',
    suitableFor: ['none'],
    contraindications: ['gastritis'],
  },
  {
    name: '回锅肉',
    description: '四川传统名菜',
    category: '荤菜',
    difficulty: 'medium',
    cookingTime: 30,
    servings: 2,
    ingredients: [
      { name: '五花肉', amount: 300, unit: 'g' },
      { name: '青蒜', amount: 150, unit: 'g' },
      { name: '郫县豆瓣酱', amount: 25, unit: 'g' },
      { name: '甜面酱', amount: 15, unit: 'g' },
    ],
    steps: ['五花肉煮至七成熟', '切片煸炒出油', '加豆瓣酱甜面酱', '加入青蒜翻炒'],
    tags: ['荤菜', '川菜', '下饭'],
    taste: 'savory',
    suitableFor: ['none'],
    contraindications: ['hypertension', 'hyperlipidemia', 'obesity'],
  },
  {
    name: '鱼香肉丝',
    description: '酸甜微辣的川菜',
    category: '荤菜',
    difficulty: 'medium',
    cookingTime: 20,
    servings: 2,
    ingredients: [
      { name: '猪肉丝', amount: 200, unit: 'g' },
      { name: '木耳', amount: 50, unit: 'g' },
      { name: '胡萝卜丝', amount: 50, unit: 'g' },
      { name: '泡椒', amount: 20, unit: 'g' },
      { name: '葱姜蒜', amount: 40, unit: 'g' },
    ],
    steps: ['肉丝腌制', '木耳胡萝卜切丝', '炒肉丝加泡椒', '加入配菜调味'],
    tags: ['荤菜', '川菜', '下饭'],
    taste: 'spicy',
    suitableFor: ['all'],
    contraindications: [],
  },
  {
    name: '红烧排骨',
    description: '酱香浓郁的红烧排骨',
    category: '荤菜',
    difficulty: 'medium',
    cookingTime: 45,
    servings: 3,
    ingredients: [
      { name: '排骨', amount: 500, unit: 'g' },
      { name: '酱油', amount: 40, unit: 'ml' },
      { name: '冰糖', amount: 20, unit: 'g' },
      { name: '姜', amount: 20, unit: 'g' },
      { name: '葱', amount: 30, unit: 'g' },
    ],
    steps: ['排骨焯水', '炒糖色放排骨', '加酱油姜葱', '加水炖40分钟'],
    tags: ['荤菜', '硬菜', '高蛋白'],
    taste: 'rich',
    suitableFor: ['none'],
    contraindications: ['hyperlipidemia', 'obesity'],
  },
  {
    name: '糖醋排骨',
    description: '酸甜可口的排骨',
    category: '荤菜',
    difficulty: 'medium',
    cookingTime: 40,
    servings: 3,
    ingredients: [
      { name: '排骨', amount: 500, unit: 'g' },
      { name: '糖', amount: 50, unit: 'g' },
      { name: '醋', amount: 40, unit: 'ml' },
      { name: '酱油', amount: 20, unit: 'ml' },
      { name: '姜', amount: 15, unit: 'g' },
    ],
    steps: ['排骨焯水', '炒糖色', '加醋酱油姜', '加水炖30分钟', '收汁'],
    tags: ['荤菜', '酸甜', '下饭'],
    taste: 'sweet',
    suitableFor: ['none'],
    contraindications: ['diabetes', 'hyperlipidemia'],
  },
  {
    name: '黄焖鸡',
    description: '鲜嫩多汁的黄焖鸡',
    category: '荤菜',
    difficulty: 'medium',
    cookingTime: 30,
    servings: 3,
    ingredients: [
      { name: '鸡腿肉', amount: 400, unit: 'g' },
      { name: '香菇', amount: 100, unit: 'g' },
      { name: '青椒', amount: 100, unit: 'g' },
      { name: '姜', amount: 20, unit: 'g' },
      { name: '酱油', amount: 30, unit: 'ml' },
    ],
    steps: ['鸡肉切块', '爆香姜片', '下鸡肉翻炒', '加香菇酱油焖煮', '加青椒'],
    tags: ['荤菜', '焖菜', '下饭'],
    taste: 'savory',
    suitableFor: ['all'],
    contraindications: [],
  },
  {
    name: '板栗烧鸡',
    description: '香甜可口的板栗烧鸡',
    category: '荤菜',
    difficulty: 'medium',
    cookingTime: 40,
    servings: 3,
    ingredients: [
      { name: '鸡腿肉', amount: 400, unit: 'g' },
      { name: '板栗', amount: 200, unit: 'g' },
      { name: '酱油', amount: 30, unit: 'ml' },
      { name: '姜', amount: 20, unit: 'g' },
      { name: '葱', amount: 30, unit: 'g' },
    ],
    steps: ['鸡肉切块', '板栗去皮', '爆香姜片', '下鸡肉翻炒', '加板栗酱油焖煮'],
    tags: ['荤菜', '焖菜', '秋季'],
    taste: 'savory',
    suitableFor: ['all'],
    contraindications: [],
  },
  {
    name: '小炒肉',
    description: '湖南特色小炒',
    category: '荤菜',
    difficulty: 'easy',
    cookingTime: 15,
    servings: 2,
    ingredients: [
      { name: '猪肉', amount: 200, unit: 'g' },
      { name: '青蒜', amount: 100, unit: 'g' },
      { name: '小米椒', amount: 30, unit: 'g' },
      { name: '豆豉', amount: 15, unit: 'g' },
    ],
    steps: ['猪肉切片', '青蒜切段', '热锅爆炒肉片', '加辣椒豆豉青蒜'],
    tags: ['荤菜', '湘菜', '下饭'],
    taste: 'spicy',
    suitableFor: ['none'],
    contraindications: ['gastritis'],
  },
  {
    name: '水煮肉片',
    description: '麻辣鲜香的川菜',
    category: '荤菜',
    difficulty: 'hard',
    cookingTime: 25,
    servings: 4,
    ingredients: [
      { name: '猪里脊', amount: 300, unit: 'g' },
      { name: '豆芽', amount: 200, unit: 'g' },
      { name: '干辣椒', amount: 30, unit: 'g' },
      { name: '花椒', amount: 15, unit: 'g' },
      { name: '郫县豆瓣酱', amount: 50, unit: 'g' },
    ],
    steps: ['肉片成片腌制', '炒香豆瓣酱加水', '豆芽焯水垫底', '煮肉片捞出', '浇热油'],
    tags: ['荤菜', '川菜', '麻辣'],
    taste: 'spicy',
    suitableFor: ['none'],
    contraindications: ['gastritis', 'renal_disease'],
  },
  {
    name: '蒜香排骨',
    description: '蒜香浓郁的排骨',
    category: '荤菜',
    difficulty: 'medium',
    cookingTime: 40,
    servings: 3,
    ingredients: [
      { name: '肋排', amount: 500, unit: 'g' },
      { name: '蒜', amount: 100, unit: 'g' },
      { name: '盐', amount: 5, unit: 'g' },
      { name: '胡椒粉', amount: 3, unit: 'g' },
    ],
    steps: ['排骨焯水', '蒜蓉涂抹排骨', '腌制30分钟', '烤箱或空气炸锅180度20分钟'],
    tags: ['荤菜', '烤制', '蒜香'],
    taste: 'savory',
    suitableFor: ['all'],
    contraindications: [],
  },
  {
    name: '啤酒鸭',
    description: '用啤酒烹制的鸭子',
    category: '荤菜',
    difficulty: 'medium',
    cookingTime: 60,
    servings: 4,
    ingredients: [
      { name: '鸭肉', amount: 600, unit: 'g' },
      { name: '啤酒', amount: 330, unit: 'ml' },
      { name: '姜', amount: 30, unit: 'g' },
      { name: '辣椒', amount: 50, unit: 'g' },
      { name: '蒜', amount: 30, unit: 'g' },
    ],
    steps: ['鸭肉切块焯水', '爆香姜蒜辣椒', '下鸭肉翻炒', '加啤酒焖煮50分钟'],
    tags: ['荤菜', '啤酒', '焖菜'],
    taste: 'savory',
    suitableFor: ['all'],
    contraindications: [],
  },
  {
    name: '孜然羊肉',
    description: '新疆风味羊肉',
    category: '荤菜',
    difficulty: 'medium',
    cookingTime: 20,
    servings: 2,
    ingredients: [
      { name: '羊肉', amount: 300, unit: 'g' },
      { name: '孜然粉', amount: 15, unit: 'g' },
      { name: '辣椒粉', amount: 10, unit: 'g' },
      { name: '洋葱', amount: 100, unit: 'g' },
      { name: '香菜', amount: 50, unit: 'g' },
    ],
    steps: ['羊肉切片腌制', '热锅爆炒羊肉', '加入孜然辣椒', '加入洋葱翻炒', '撒香菜'],
    tags: ['荤菜', '新疆', '孜然'],
    taste: 'spicy',
    suitableFor: ['all'],
    contraindications: [],
  },
  {
    name: '酱爆鸡丁',
    description: '酱香浓郁的鸡丁',
    category: '荤菜',
    difficulty: 'easy',
    cookingTime: 15,
    servings: 2,
    ingredients: [
      { name: '鸡胸肉', amount: 200, unit: 'g' },
      { name: '甜面酱', amount: 30, unit: 'g' },
      { name: '黄瓜', amount: 100, unit: 'g' },
      { name: '花生', amount: 50, unit: 'g' },
    ],
    steps: ['鸡肉切丁', '甜面酱炒香', '下鸡丁翻炒', '加黄瓜丁花生'],
    tags: ['荤菜', '酱爆', '下饭'],
    taste: 'savory',
    suitableFor: ['all'],
    contraindications: [],
  },
  {
    name: '东坡肉',
    description: '杭州传统名菜',
    category: '荤菜',
    difficulty: 'hard',
    cookingTime: 120,
    servings: 4,
    ingredients: [
      { name: '五花肉', amount: 600, unit: 'g' },
      { name: '酱油', amount: 50, unit: 'ml' },
      { name: '冰糖', amount: 40, unit: 'g' },
      { name: '黄酒', amount: 200, unit: 'ml' },
      { name: '姜', amount: 30, unit: 'g' },
    ],
    steps: ['五花肉切方块', '扎孔以便入味', '砂锅铺姜片', '放入肉加黄酒糖酱油', '小火炖2小时'],
    tags: ['荤菜', '浙菜', '传统'],
    taste: 'rich',
    suitableFor: ['none'],
    contraindications: ['hypertension', 'hyperlipidemia', 'obesity'],
  },
  {
    name: '梅菜扣肉',
    description: '广东传统名菜',
    category: '荤菜',
    difficulty: 'hard',
    cookingTime: 90,
    servings: 6,
    ingredients: [
      { name: '五花肉', amount: 500, unit: 'g' },
      { name: '梅干菜', amount: 100, unit: 'g' },
      { name: '酱油', amount: 40, unit: 'ml' },
      { name: '糖', amount: 20, unit: 'g' },
      { name: '姜', amount: 20, unit: 'g' },
    ],
    steps: ['五花肉煮至七成熟', '梅干菜泡发', '肉片抹酱油炸至金黄', '梅干菜铺底肉片覆盖', '蒸60分钟'],
    tags: ['荤菜', '粤菜', '传统'],
    taste: 'savory',
    suitableFor: ['none'],
    contraindications: ['hypertension', 'hyperlipidemia'],
  },

  // ========== 海鲜 (Seafood) ==========
  {
    name: '清蒸鲈鱼',
    description: '鲜嫩可口的清蒸鱼',
    category: '水产',
    difficulty: 'medium',
    cookingTime: 20,
    servings: 3,
    ingredients: [
      { name: '鲈鱼', amount: 500, unit: 'g' },
      { name: '姜', amount: 30, unit: 'g' },
      { name: '葱', amount: 30, unit: 'g' },
      { name: '蒸鱼豉油', amount: 30, unit: 'ml' },
      { name: '油', amount: 30, unit: 'ml' },
    ],
    steps: ['鱼处理干净', '姜葱切丝', '水开后放入蒸8-10分钟', '倒掉汤汁淋蒸鱼豉油', '热油浇葱姜'],
    tags: ['水产', '清蒸', '高蛋白'],
    taste: 'light',
    suitableFor: ['all'],
    contraindications: [],
  },
  {
    name: '红烧鲤鱼',
    description: '家常红烧鱼',
    category: '水产',
    difficulty: 'medium',
    cookingTime: 25,
    servings: 3,
    ingredients: [
      { name: '鲤鱼', amount: 600, unit: 'g' },
      { name: '酱油', amount: 30, unit: 'ml' },
      { name: '糖', amount: 15, unit: 'g' },
      { name: '姜', amount: 20, unit: 'g' },
      { name: '葱', amount: 30, unit: 'g' },
    ],
    steps: ['鱼处理干净', '热锅下油煎鱼', '加酱油糖姜葱', '加水焖煮15分钟'],
    tags: ['水产', '红烧', '家常'],
    taste: 'savory',
    suitableFor: ['all'],
    contraindications: [],
  },
  {
    name: '蒜蓉虾',
    description: '蒜香浓郁的虾',
    category: '水产',
    difficulty: 'easy',
    cookingTime: 15,
    servings: 2,
    ingredients: [
      { name: '基围虾', amount: 300, unit: 'g' },
      { name: '蒜', amount: 50, unit: 'g' },
      { name: '葱', amount: 30, unit: 'g' },
      { name: '油', amount: 30, unit: 'ml' },
      { name: '盐', amount: 3, unit: 'g' },
    ],
    steps: ['虾洗净去虾线', '蒜蓉爆香', '下虾翻炒', '撒葱花出锅'],
    tags: ['水产', '蒜蓉', '高蛋白'],
    taste: 'savory',
    suitableFor: ['all'],
    contraindications: [],
  },
  {
    name: '油焖大虾',
    description: '胶东名菜',
    category: '水产',
    difficulty: 'medium',
    cookingTime: 20,
    servings: 2,
    ingredients: [
      { name: '大虾', amount: 400, unit: 'g' },
      { name: '番茄酱', amount: 30, unit: 'g' },
      { name: '糖', amount: 20, unit: 'g' },
      { name: '姜', amount: 15, unit: 'g' },
      { name: '葱', amount: 20, unit: 'g' },
    ],
    steps: ['虾洗净去虾线', '热锅下油煎虾', '加番茄酱糖姜葱', '加盖焖煮10分钟'],
    tags: ['水产', '鲁菜', '油焖'],
    taste: 'savory',
    suitableFor: ['all'],
    contraindications: [],
  },
  {
    name: '香辣蟹',
    description: '香辣可口的蟹',
    category: '水产',
    difficulty: 'medium',
    cookingTime: 25,
    servings: 3,
    ingredients: [
      { name: '梭子蟹', amount: 600, unit: 'g' },
      { name: '干辣椒', amount: 30, unit: 'g' },
      { name: '花椒', amount: 10, unit: 'g' },
      { name: '姜', amount: 30, unit: 'g' },
      { name: '蒜', amount: 50, unit: 'g' },
    ],
    steps: ['蟹处理干净切块', '油炸至变色', '爆香辣椒花椒姜蒜', '加入蟹块翻炒'],
    tags: ['水产', '香辣', '秋季'],
    taste: 'spicy',
    suitableFor: ['all'],
    contraindications: [],
  },
  {
    name: '葱姜炒蟹',
    description: '原汁原味的炒蟹',
    category: '水产',
    difficulty: 'easy',
    cookingTime: 15,
    servings: 2,
    ingredients: [
      { name: '螃蟹', amount: 400, unit: 'g' },
      { name: '葱', amount: 50, unit: 'g' },
      { name: '姜', amount: 30, unit: 'g' },
      { name: '油', amount: 30, unit: 'ml' },
    ],
    steps: ['蟹处理干净', '葱切段姜切丝', '热锅爆香葱姜', '下蟹翻炒'],
    tags: ['水产', '葱姜', '原味'],
    taste: 'light',
    suitableFor: ['all'],
    contraindications: [],
  },
  {
    name: '清蒸大闸蟹',
    description: '秋季美食',
    category: '水产',
    difficulty: 'easy',
    cookingTime: 20,
    servings: 2,
    ingredients: [
      { name: '大闸蟹', amount: 3, unit: '只' },
      { name: '姜', amount: 30, unit: 'g' },
      { name: '醋', amount: 30, unit: 'ml' },
    ],
    steps: ['螃蟹洗净', '水开后放入', '蒸15-20分钟', '姜醋蘸料'],
    tags: ['水产', '秋季', '高端'],
    taste: 'light',
    suitableFor: ['all'],
    contraindications: [],
  },
  {
    name: '三文鱼刺身',
    description: '新鲜的生鱼片',
    category: '水产',
    difficulty: 'medium',
    cookingTime: 5,
    servings: 2,
    ingredients: [
      { name: '三文鱼', amount: 200, unit: 'g' },
      { name: '芥末', amount: 10, unit: 'g' },
      { name: '酱油', amount: 30, unit: 'ml' },
    ],
    steps: ['三文鱼冷藏', '切成薄片', '摆盘', '蘸芥末酱油食用'],
    tags: ['水产', '刺身', '日式'],
    taste: 'light',
    suitableFor: ['all'],
    contraindications: [],
  },
  {
    name: '香煎三文鱼',
    description: '外焦里嫩的三文鱼',
    category: '水产',
    difficulty: 'easy',
    cookingTime: 15,
    servings: 2,
    ingredients: [
      { name: '三文鱼', amount: 300, unit: 'g' },
      { name: '柠檬', amount: 1, unit: '个' },
      { name: '盐', amount: 3, unit: 'g' },
      { name: '黑胡椒', amount: 2, unit: 'g' },
      { name: '油', amount: 20, unit: 'ml' },
    ],
    steps: ['三文鱼用盐胡椒腌制', '热锅下油', '鱼皮朝下煎3分钟', '翻面煎2分钟', '挤柠檬汁'],
    tags: ['水产', '煎制', '高蛋白'],
    taste: 'light',
    suitableFor: ['all'],
    contraindications: [],
  },
  {
    name: '酱爆鱿鱼',
    description: '鲜嫩的酱爆鱿鱼',
    category: '水产',
    difficulty: 'easy',
    cookingTime: 15,
    servings: 2,
    ingredients: [
      { name: '鱿鱼', amount: 300, unit: 'g' },
      { name: '甜面酱', amount: 30, unit: 'g' },
      { name: '青椒', amount: 100, unit: 'g' },
      { name: '洋葱', amount: 100, unit: 'g' },
      { name: '姜', amount: 15, unit: 'g' },
    ],
    steps: ['鱗鱼切花刀', '焯水至卷曲', '甜面酱炒香', '加入配菜翻炒', '加入鱗鱼'],
    tags: ['水产', '酱爆', '快手'],
    taste: 'savory',
    suitableFor: ['all'],
    contraindications: [],
  },
  {
    name: '爆炒花甲',
    description: '鲜美的花甲',
    category: '水产',
    difficulty: 'easy',
    cookingTime: 10,
    servings: 2,
    ingredients: [
      { name: '花甲', amount: 500, unit: 'g' },
      { name: '辣椒', amount: 30, unit: 'g' },
      { name: '蒜', amount: 30, unit: 'g' },
      { name: '葱', amount: 20, unit: 'g' },
      { name: '料酒', amount: 20, unit: 'ml' },
    ],
    steps: ['花甲吐沙洗净', '热锅爆香辣椒蒜', '下花甲翻炒', '加料酒焖至开口', '撒葱出锅'],
    tags: ['水产', '快手', '海鲜'],
    taste: 'savory',
    suitableFor: ['all'],
    contraindications: [],
  },
  {
    name: '粉丝蒸扇贝',
    description: '鲜美的蒸扇贝',
    category: '水产',
    difficulty: 'medium',
    cookingTime: 15,
    servings: 2,
    ingredients: [
      { name: '扇贝', amount: 6, unit: '个' },
      { name: '粉丝', amount: 50, unit: 'g' },
      { name: '蒜', amount: 50, unit: 'g' },
      { name: '酱油', amount: 20, unit: 'ml' },
      { name: '葱', amount: 20, unit: 'g' },
    ],
    steps: ['扇贝洗净', '粉丝泡软', '蒜蓉加酱油拌匀', '粉丝放扇贝上', '蒸8分钟淋蒜蓉'],
    tags: ['水产', '蒸制', '粤菜'],
    taste: 'savory',
    suitableFor: ['all'],
    contraindications: [],
  },
  {
    name: '辣炒蛏子',
    description: '香辣可口的蛏子',
    category: '水产',
    difficulty: 'easy',
    cookingTime: 10,
    servings: 2,
    ingredients: [
      { name: '蛏子', amount: 400, unit: 'g' },
      { name: '干辣椒', amount: 20, unit: 'g' },
      { name: '蒜', amount: 30, unit: 'g' },
      { name: '葱', amount: 20, unit: 'g' },
      { name: '料酒', amount: 20, unit: 'ml' },
    ],
    steps: ['蛏子洗净', '热锅爆香辣椒蒜', '下蛏子翻炒', '加料酒焖至开口', '撒葱出锅'],
    tags: ['水产', '辣炒', '快手'],
    taste: 'spicy',
    suitableFor: ['all'],
    contraindications: [],
  },
  {
    name: '清蒸多宝鱼',
    description: '高端海鲜',
    category: '水产',
    difficulty: 'medium',
    cookingTime: 20,
    servings: 3,
    ingredients: [
      { name: '多宝鱼', amount: 500, unit: 'g' },
      { name: '姜', amount: 30, unit: 'g' },
      { name: '葱', amount: 30, unit: 'g' },
      { name: '蒸鱼豉油', amount: 30, unit: 'ml' },
    ],
    steps: ['鱼处理干净', '姜葱切丝', '水开后放入蒸10分钟', '倒汤汁淋豉油', '热油浇葱姜'],
    tags: ['水产', '清蒸', '高端'],
    taste: 'light',
    suitableFor: ['all'],
    contraindications: [],
  },
  {
    name: '糖醋鱼块',
    description: '酸甜可口的鱼块',
    category: '水产',
    difficulty: 'medium',
    cookingTime: 20,
    servings: 3,
    ingredients: [
      { name: '鱼块', amount: 400, unit: 'g' },
      { name: '番茄酱', amount: 40, unit: 'g' },
      { name: '糖', amount: 30, unit: 'g' },
      { name: '醋', amount: 20, unit: 'ml' },
      { name: '淀粉', amount: 50, unit: 'g' },
    ],
    steps: ['鱼块裹淀粉', '油炸至金黄', '糖醋汁加热', '鱼块裹汁'],
    tags: ['水产', '酸甜', '下饭'],
    taste: 'sweet',
    suitableFor: ['all'],
    contraindications: [],
  },

  // ========== 主食类 (Staples) ==========
  {
    name: '蛋炒饭',
    description: '经典的中式蛋炒饭',
    category: '主食',
    difficulty: 'easy',
    cookingTime: 10,
    servings: 1,
    ingredients: [
      { name: '米饭', amount: 200, unit: 'g' },
      { name: '鸡蛋', amount: 2, unit: '个' },
      { name: '葱', amount: 20, unit: 'g' },
      { name: '盐', amount: 3, unit: 'g' },
      { name: '油', amount: 15, unit: 'ml' },
    ],
    steps: ['鸡蛋打散，米饭弄散', '热锅下油炒蛋液', '加入米饭翻炒', '加盐调味撒葱花'],
    tags: ['主食', '快捷', '经典'],
    taste: 'savory',
    suitableFor: ['all'],
    contraindications: ['egg'],
  },
  {
    name: '扬州炒饭',
    description: '配料丰富的炒饭',
    category: '主食',
    difficulty: 'medium',
    cookingTime: 15,
    servings: 2,
    ingredients: [
      { name: '米饭', amount: 400, unit: 'g' },
      { name: '鸡蛋', amount: 2, unit: '个' },
      { name: '火腿', amount: 50, unit: 'g' },
      { name: '虾仁', amount: 50, unit: 'g' },
      { name: '青豆', amount: 30, unit: 'g' },
      { name: '胡萝卜', amount: 30, unit: 'g' },
    ],
    steps: ['配料切丁', '鸡蛋炒散', '加入配料翻炒', '加入米饭翻炒', '加盐调味'],
    tags: ['主食', '淮扬', '丰富'],
    taste: 'savory',
    suitableFor: ['all'],
    contraindications: ['egg', 'shellfish'],
  },
  {
    name: '酱油炒面',
    description: '经典的中式炒面',
    category: '主食',
    difficulty: 'easy',
    cookingTime: 15,
    servings: 1,
    ingredients: [
      { name: '面条', amount: 150, unit: 'g' },
      { name: '青菜', amount: 100, unit: 'g' },
      { name: '肉丝', amount: 50, unit: 'g' },
      { name: '酱油', amount: 20, unit: 'ml' },
      { name: '油', amount: 15, unit: 'ml' },
    ],
    steps: ['面条煮至八成熟', '肉丝青菜炒熟', '下面条翻炒', '加酱油调味'],
    tags: ['主食', '快捷', '街头'],
    taste: 'savory',
    suitableFor: ['all'],
    contraindications: [],
  },
  {
    name: '葱油拌面',
    description: '上海特色面食',
    category: '主食',
    difficulty: 'easy',
    cookingTime: 15,
    servings: 1,
    ingredients: [
      { name: '细面条', amount: 100, unit: 'g' },
      { name: '小葱', amount: 50, unit: 'g' },
      { name: '油', amount: 40, unit: 'ml' },
      { name: '酱油', amount: 20, unit: 'ml' },
    ],
    steps: ['面条煮熟', '葱切段用油炸香', '加酱油入葱油', '拌面食用'],
    tags: ['主食', '沪菜', '特色'],
    taste: 'savory',
    suitableFor: ['all'],
    contraindications: [],
  },
  {
    name: '打卤面',
    description: '北方经典面食',
    category: '主食',
    difficulty: 'medium',
    cookingTime: 30,
    servings: 2,
    ingredients: [
      { name: '面条', amount: 200, unit: 'g' },
      { name: '木耳', amount: 30, unit: 'g' },
      { name: '黄花菜', amount: 30, unit: 'g' },
      { name: '肉片', amount: 50, unit: 'g' },
      { name: '鸡蛋', amount: 2, unit: '个' },
    ],
    steps: ['配料泡发切片', '肉片炒香', '加水煮配料', '加入蛋液勾芡', '浇在煮好的面上'],
    tags: ['主食', '北方面', '经典'],
    taste: 'savory',
    suitableFor: ['all'],
    contraindications: ['egg'],
  },
  {
    name: '炸酱面',
    description: '北京特色面食',
    category: '主食',
    difficulty: 'medium',
    cookingTime: 30,
    servings: 2,
    ingredients: [
      { name: '面条', amount: 200, unit: 'g' },
      { name: '猪肉末', amount: 150, unit: 'g' },
      { name: '黄酱', amount: 80, unit: 'g' },
      { name: '黄瓜', amount: 100, unit: 'g' },
      { name: '胡萝卜', amount: 50, unit: 'g' },
    ],
    steps: ['黄酱加水上锅蒸', '肉末炒散', '加蒸好的黄酱', '面条煮熟', '配菜切丝拌面'],
    tags: ['主食', '京菜', '传统'],
    taste: 'savory',
    suitableFor: ['all'],
    contraindications: [],
  },
  {
    name: '热干面',
    description: '武汉特色早餐',
    category: '主食',
    difficulty: 'medium',
    cookingTime: 15,
    servings: 1,
    ingredients: [
      { name: '碱面', amount: 150, unit: 'g' },
      { name: '芝麻酱', amount: 30, unit: 'g' },
      { name: '酸豆角', amount: 30, unit: 'g' },
      { name: '葱', amount: 20, unit: 'g' },
      { name: '酱油', amount: 15, unit: 'ml' },
    ],
    steps: ['面条煮熟', '芝麻酱加酱油调稀', '面条沥干加芝麻酱', '加酸豆角葱花'],
    tags: ['主食', '武汉', '早餐'],
    taste: 'savory',
    suitableFor: ['all'],
    contraindications: [],
  },
  {
    name: '担担面',
    description: '四川特色面食',
    category: '主食',
    difficulty: 'medium',
    cookingTime: 20,
    servings: 1,
    ingredients: [
      { name: '细面条', amount: 100, unit: 'g' },
      { name: '猪肉末', amount: 50, unit: 'g' },
      { name: '花生碎', amount: 20, unit: 'g' },
      { name: '辣椒油', amount: 20, unit: 'ml' },
      { name: '花椒粉', amount: 2, unit: 'g' },
      { name: '酱油', amount: 15, unit: 'ml' },
    ],
    steps: ['肉末炒香', '面条煮熟', '调料碗底', '加入面条', '撒肉末花生'],
    tags: ['主食', '川菜', '特色'],
    taste: 'spicy',
    suitableFor: ['none'],
    contraindications: ['gastritis'],
  },
  {
    name: '炒河粉',
    description: '广东经典主食',
    category: '主食',
    difficulty: 'medium',
    cookingTime: 15,
    servings: 1,
    ingredients: [
      { name: '河粉', amount: 200, unit: 'g' },
      { name: '牛肉', amount: 50, unit: 'g' },
      { name: '豆芽', amount: 100, unit: 'g' },
      { name: '韭黄', amount: 50, unit: 'g' },
      { name: '酱油', amount: 20, unit: 'ml' },
    ],
    steps: ['牛肉切片腌制', '河粉轻轻拨散', '大火快炒河粉', '加入牛肉豆芽', '加酱油调味'],
    tags: ['主食', '粤菜', '快手'],
    taste: 'savory',
    suitableFor: ['all'],
    contraindications: [],
  },
  {
    name: '盖浇饭',
    description: '快餐经典',
    category: '主食',
    difficulty: 'easy',
    cookingTime: 20,
    servings: 1,
    ingredients: [
      { name: '米饭', amount: 200, unit: 'g' },
      { name: '肉片', amount: 100, unit: 'g' },
      { name: '青菜', amount: 100, unit: 'g' },
      { name: '酱油', amount: 20, unit: 'ml' },
      { name: '淀粉', amount: 10, unit: 'g' },
    ],
    steps: ['肉片腌制', '肉片炒熟', '青菜焯水', '淀粉勾芡', '浇在米饭上'],
    tags: ['主食', '快餐', '方便'],
    taste: 'savory',
    suitableFor: ['all'],
    contraindications: [],
  },

  // ========== 甜品/饮品 (Desserts/Beverages) ==========
  {
    name: '红枣银耳羹',
    description: '美容养颜的甜品',
    category: '甜品',
    difficulty: 'medium',
    cookingTime: 60,
    servings: 4,
    ingredients: [
      { name: '银耳', amount: 30, unit: 'g' },
      { name: '红枣', amount: 10, unit: '颗' },
      { name: '枸杞', amount: 10, unit: 'g' },
      { name: '冰糖', amount: 30, unit: 'g' },
    ],
    steps: ['银耳泡发撕小朵', '加水煮银耳30分钟', '加入红枣枸杞', '加冰糖再煮20分钟'],
    tags: ['甜品', '养颜', '滋补'],
    taste: 'sweet',
    suitableFor: ['all'],
    contraindications: ['diabetes'],
  },
  {
    name: '双皮奶',
    description: '广式甜品',
    category: '甜品',
    difficulty: 'medium',
    cookingTime: 30,
    servings: 2,
    ingredients: [
      { name: '牛奶', amount: 300, unit: 'ml' },
      { name: '蛋清', amount: 2, unit: '个' },
      { name: '糖', amount: 30, unit: 'g' },
    ],
    steps: ['牛奶加热放凉起皮', '蛋清加糖打散', '蛋清液倒入牛奶', '小火蒸15分钟'],
    tags: ['甜品', '粤菜', '嫩滑'],
    taste: 'sweet',
    suitableFor: ['all'],
    contraindications: ['egg', 'lactose_intolerant'],
  },
  {
    name: '酒酿圆子',
    description: '江南甜品',
    category: '甜品',
    difficulty: 'easy',
    cookingTime: 15,
    servings: 2,
    ingredients: [
      { name: '酒酿', amount: 200, unit: 'g' },
      { name: '小圆子', amount: 100, unit: 'g' },
      { name: '鸡蛋', amount: 1, unit: '个' },
      { name: '糖', amount: 20, unit: 'g' },
    ],
    steps: ['水开后下圆子', '煮至浮起', '加入酒酿', '加入蛋液', '加糖调味'],
    tags: ['甜品', '江南', '传统'],
    taste: 'sweet',
    suitableFor: ['all'],
    contraindications: ['egg', 'alcohol'],
  },
  {
    name: '芋圆西米露',
    description: '台湾甜品',
    category: '甜品',
    difficulty: 'medium',
    cookingTime: 30,
    servings: 2,
    ingredients: [
      { name: '芋圆', amount: 100, unit: 'g' },
      { name: '西米', amount: 50, unit: 'g' },
      { name: '椰奶', amount: 200, unit: 'ml' },
      { name: '糖', amount: 20, unit: 'g' },
    ],
    steps: ['西米煮至透明', '芋圆煮熟', '捞出放入椰奶', '加糖调味'],
    tags: ['甜品', '台式', '夏季'],
    taste: 'sweet',
    suitableFor: ['all'],
    contraindications: ['diabetes'],
  },
  {
    name: '绿豆汤',
    description: '夏季消暑饮品',
    category: '甜品',
    difficulty: 'easy',
    cookingTime: 40,
    servings: 4,
    ingredients: [
      { name: '绿豆', amount: 100, unit: 'g' },
      { name: '冰糖', amount: 30, unit: 'g' },
      { name: '水', amount: 1000, unit: 'ml' },
    ],
    steps: ['绿豆洗净浸泡', '加水大火煮沸', '转小火煮30分钟', '加冰糖调味'],
    tags: ['甜品', '消暑', '夏季'],
    taste: 'sweet',
    suitableFor: ['all', 'weight_loss'],
    contraindications: [],
  },
  {
    name: '冰糖雪梨',
    description: '润肺止咳饮品',
    category: '甜品',
    difficulty: 'easy',
    cookingTime: 30,
    servings: 1,
    ingredients: [
      { name: '雪梨', amount: 1, unit: '个' },
      { name: '冰糖', amount: 20, unit: 'g' },
      { name: '枸杞', amount: 5, unit: 'g' },
    ],
    steps: ['雪梨去皮切块', '加水放入梨块', '加冰糖枸杞', '煮20分钟'],
    tags: ['甜品', '润肺', '养生'],
    taste: 'sweet',
    suitableFor: ['all'],
    contraindications: ['diabetes'],
  },
  {
    name: '杨枝甘露',
    description: '港式甜品',
    category: '甜品',
    difficulty: 'medium',
    cookingTime: 20,
    servings: 2,
    ingredients: [
      { name: '芒果', amount: 200, unit: 'g' },
      { name: '椰浆', amount: 100, unit: 'ml' },
      { name: '西柚', amount: 50, unit: 'g' },
      { name: '西米', amount: 30, unit: 'g' },
      { name: '淡奶油', amount: 50, unit: 'ml' },
    ],
    steps: ['西米煮熟', '芒果打泥', '椰浆淡奶油混合', '加入芒果泥', '加入西米西柚'],
    tags: ['甜品', '港式', '经典'],
    taste: 'sweet',
    suitableFor: ['all'],
    contraindications: ['diabetes'],
  },
  {
    name: '珍珠奶茶',
    description: '台湾特色饮品',
    category: '甜品',
    difficulty: 'medium',
    cookingTime: 30,
    servings: 2,
    ingredients: [
      { name: '红茶', amount: 10, unit: 'g' },
      { name: '牛奶', amount: 300, unit: 'ml' },
      { name: '珍珠', amount: 100, unit: 'g' },
      { name: '糖', amount: 30, unit: 'g' },
    ],
    steps: ['红茶泡开', '加入牛奶', '珍珠煮熟', '杯底放珍珠', '倒入奶茶加糖'],
    tags: ['甜品', '台式', '饮品'],
    taste: 'sweet',
    suitableFor: ['none'],
    contraindications: ['diabetes', 'lactose_intolerant'],
  },

  // ========== 更多早餐 ==========
  { name: '油条', description: '酥脆的传统油条', category: '早餐', difficulty: 'hard', cookingTime: 60, servings: 4, ingredients: [{ name: '面粉', amount: 500, unit: 'g' }, { name: '酵母', amount: 5, unit: 'g' }, { name: '盐', amount: 5, unit: 'g' }, { name: '泡打粉', amount: 5, unit: 'g' }], steps: ['和面醒发2小时', '擀成薄片切条', '油炸至金黄'], tags: ['早餐', '油炸'], taste: 'savory', suitableFor: ['none'], contraindications: ['obesity'] },
  { name: '煎饼果子', description: '天津特色早餐', category: '早餐', difficulty: 'medium', cookingTime: 15, servings: 1, ingredients: [{ name: '面粉', amount: 50, unit: 'g' }, { name: '鸡蛋', amount: 1, unit: '个' }, { name: '油条', amount: 1, unit: '根' }, { name: '葱', amount: 10, unit: 'g' }], steps: ['摊饼打鸡蛋', '刷甜面酱', '卷入油条'], tags: ['早餐', '天津'], taste: 'savory', suitableFor: ['none'], contraindications: [] },
  { name: '手抓饼', description: '外酥里层的手抓饼', category: '早餐', difficulty: 'medium', cookingTime: 20, servings: 1, ingredients: [{ name: '面粉', amount: 150, unit: 'g' }, { name: '黄油', amount: 30, unit: 'g' }, { name: '鸡蛋', amount: 1, unit: '个' }], steps: ['和面擀薄抹黄油', '卷起擀平', '煎至金黄加鸡蛋'], tags: ['早餐', '酥脆'], taste: 'savory', suitableFor: ['none'], contraindications: [] },
  { name: '鸡蛋堡', description: '营养丰富的鸡蛋堡', category: '早餐', difficulty: 'easy', cookingTime: 15, servings: 1, ingredients: [{ name: '面粉', amount: 80, unit: 'g' }, { name: '鸡蛋', amount: 2, unit: '个' }, { name: '火腿', amount: 30, unit: 'g' }], steps: ['面糊摊饼', '打鸡蛋火腿', '翻面煎熟'], tags: ['早餐', '营养'], taste: 'savory', suitableFor: ['all'], contraindications: [] },
  { name: '土豆丝饼', description: '香脆的土豆丝饼', category: '早餐', difficulty: 'easy', cookingTime: 20, servings: 2, ingredients: [{ name: '土豆', amount: 200, unit: 'g' }, { name: '面粉', amount: 50, unit: 'g' }, { name: '鸡蛋', amount: 1, unit: '个' }], steps: ['土豆擦丝加面粉', '搅匀成糊', '煎至两面金黄'], tags: ['早餐', '快手'], taste: 'savory', suitableFor: ['all'], contraindications: [] },
  { name: '肉夹馍', description: '陕西经典早餐', category: '早餐', difficulty: 'hard', cookingTime: 180, servings: 4, ingredients: [{ name: '五花肉', amount: 500, unit: 'g' }, { name: '面粉', amount: 400, unit: 'g' }, { name: '酵母', amount: 5, unit: 'g' }, { name: '青椒', amount: 100, unit: 'g' }], steps: ['肉卤2小时', '发面做饼', '肉切碎夹入饼中'], tags: ['早餐', '陕西'], taste: 'savory', suitableFor: ['all'], contraindications: [] },
  { name: '山东煎饼', description: '山东杂粮煎饼', category: '早餐', difficulty: 'medium', cookingTime: 20, servings: 1, ingredients: [{ name: '杂粮粉', amount: 80, unit: 'g' }, { name: '鸡蛋', amount: 1, unit: '个' }, { name: '薄脆', amount: 30, unit: 'g' }], steps: ['杂粮粉调糊', '摊成薄饼', '打鸡蛋放薄脆卷起'], tags: ['早餐', '山东'], taste: 'savory', suitableFor: ['all'], contraindications: [] },

  // ========== 更多荤菜 ==========
  { name: '辣子鸡', description: '干辣香脆的辣子鸡', category: '荤菜', difficulty: 'medium', cookingTime: 35, servings: 3, ingredients: [{ name: '鸡肉', amount: 400, unit: 'g' }, { name: '干辣椒', amount: 80, unit: 'g' }, { name: '花椒', amount: 10, unit: 'g' }], steps: ['鸡肉切块腌制', '炸至金黄', '干辣椒花椒爆香', '加入鸡块翻炒'], tags: ['荤菜', '川菜'], taste: 'spicy', suitableFor: ['all'], contraindications: [] },
  { name: '锅包肉', description: '东北经典酸甜口', category: '荤菜', difficulty: 'hard', cookingTime: 40, servings: 3, ingredients: [{ name: '猪里脊', amount: 300, unit: 'g' }, { name: '面粉', amount: 100, unit: 'g' }, { name: '糖', amount: 50, unit: 'g' }, { name: '醋', amount: 50, unit: 'ml' }], steps: ['肉切片腌制裹淀粉', '炸两次', '调酸甜汁', '翻炒裹汁'], tags: ['荤菜', '东北'], taste: 'sweet', suitableFor: ['all'], contraindications: [] },
  { name: '叉烧', description: '广式经典烤猪肉', category: '荤菜', difficulty: 'medium', cookingTime: 60, servings: 4, ingredients: [{ name: '猪梅肉', amount: 500, unit: 'g' }, { name: '叉烧酱', amount: 80, unit: 'g' }, { name: '蜂蜜', amount: 30, unit: 'g' }], steps: ['肉腌制过夜', '烤箱烤制', '中途刷蜂蜜', '切片'], tags: ['荤菜', '粤菜'], taste: 'sweet', suitableFor: ['all'], contraindications: [] },
  { name: '白切鸡', description: '原汁原味的广东白切鸡', category: '荤菜', difficulty: 'medium', cookingTime: 45, servings: 4, ingredients: [{ name: '三黄鸡', amount: 1000, unit: 'g' }, { name: '姜', amount: 30, unit: 'g' }, { name: '葱', amount: 30, unit: 'g' }], steps: ['鸡处理干净', '姜葱盐擦匀', '煮熟过冰水', '切块配姜葱碟'], tags: ['荤菜', '粤菜'], taste: 'light', suitableFor: ['all'], contraindications: [] },
  { name: '盐焗鸡', description: '咸香鲜嫩的客家菜', category: '荤菜', difficulty: 'medium', cookingTime: 50, servings: 4, ingredients: [{ name: '三黄鸡', amount: 1000, unit: 'g' }, { name: '粗盐', amount: 1500, unit: 'g' }, { name: '姜', amount: 20, unit: 'g' }], steps: ['鸡腌制', '姜葱放入鸡肚', '粗盐炒热包裹', '敲开取鸡'], tags: ['荤菜', '客家'], taste: 'savory', suitableFor: ['all'], contraindications: [] },
  { name: '烧鸭', description: '皮脆肉嫩的广式烧鸭', category: '荤菜', difficulty: 'hard', cookingTime: 90, servings: 4, ingredients: [{ name: '鸭子', amount: 1500, unit: 'g' }, { name: '麦芽糖', amount: 50, unit: 'g' }, { name: '白醋', amount: 50, unit: 'ml' }], steps: ['鸭子处理', '五香粉盐擦匀', '烫皮晾干刷糖醋', '烤箱烤制'], tags: ['荤菜', '粤菜'], taste: 'savory', suitableFor: ['all'], contraindications: [] },
  { name: '小炒肉', description: '香辣下饭的湖南小炒肉', category: '荤菜', difficulty: 'easy', cookingTime: 15, servings: 2, ingredients: [{ name: '五花肉', amount: 200, unit: 'g' }, { name: '青椒', amount: 100, unit: 'g' }, { name: '豆豉', amount: 10, unit: 'g' }], steps: ['肉切片', '青椒切丝', '蒜豆豉爆香', '加入肉片翻炒'], tags: ['荤菜', '湘菜'], taste: 'savory', suitableFor: ['all'], contraindications: [] },
  { name: '辣椒炒肉', description: '经典的湘菜辣椒炒肉', category: '荤菜', difficulty: 'easy', cookingTime: 15, servings: 2, ingredients: [{ name: '五花肉', amount: 150, unit: 'g' }, { name: '青椒', amount: 150, unit: 'g' }], steps: ['肉切片，青椒切丝', '蒜爆香', '肉片炒变色', '加入青椒调料'], tags: ['荤菜', '湘菜'], taste: 'savory', suitableFor: ['all'], contraindications: [] },

  // ========== 更多素菜 ==========
  { name: '蒜蓉西兰花', description: '清爽健康的蒜蓉西兰花', category: '素菜', difficulty: 'easy', cookingTime: 10, servings: 2, ingredients: [{ name: '西兰花', amount: 300, unit: 'g' }, { name: '蒜', amount: 15, unit: 'g' }], steps: ['西兰花焯水', '蒜末爆香', '加入西兰花翻炒'], tags: ['素菜', '健康'], taste: 'light', suitableFor: ['all'], contraindications: [] },
  { name: '酸辣土豆丝', description: '爽脆可口的酸辣土豆丝', category: '素菜', difficulty: 'easy', cookingTime: 15, servings: 2, ingredients: [{ name: '土豆', amount: 200, unit: 'g' }, { name: '干辣椒', amount: 10, unit: 'g' }, { name: '醋', amount: 30, unit: 'ml' }], steps: ['土豆切丝泡水', '土豆丝翻炒', '加醋和盐', '快速出锅'], tags: ['素菜', '川菜'], taste: 'spicy', suitableFor: ['all'], contraindications: [] },
  { name: '手撕包菜', description: '清脆爽口的家常素菜', category: '素菜', difficulty: 'easy', cookingTime: 10, servings: 2, ingredients: [{ name: '包菜', amount: 300, unit: 'g' }, { name: '干辣椒', amount: 10, unit: 'g' }], steps: ['包菜手撕', '爆香调料', '加入包菜大火翻炒'], tags: ['素菜', '快手'], taste: 'savory', suitableFor: ['all'], contraindications: [] },
  { name: '干煸四季豆', description: '干香入味的干煸四季豆', category: '素菜', difficulty: 'medium', cookingTime: 20, servings: 2, ingredients: [{ name: '四季豆', amount: 300, unit: 'g' }, { name: '干辣椒', amount: 15, unit: 'g' }, { name: '花椒', amount: 3, unit: 'g' }], steps: ['四季豆煸至皱缩', '加入干辣椒花椒蒜末', '翻炒出锅'], tags: ['素菜', '川菜'], taste: 'savory', suitableFor: ['all'], contraindications: [] },
  { name: '清炒空心菜', description: '清爽脆绿的清炒空心菜', category: '素菜', difficulty: 'easy', cookingTime: 5, servings: 2, ingredients: [{ name: '空心菜', amount: 400, unit: 'g' }, { name: '蒜', amount: 15, unit: 'g' }], steps: ['空心菜切段', '蒜末爆香', '加入空心菜大火翻炒'], tags: ['素菜', '快手'], taste: 'light', suitableFor: ['all'], contraindications: [] },
  { name: '香菇青菜', description: '鲜香健康的香菇青菜', category: '素菜', difficulty: 'easy', cookingTime: 10, servings: 2, ingredients: [{ name: '青菜', amount: 400, unit: 'g' }, { name: '香菇', amount: 100, unit: 'g' }], steps: ['香菇切片，青菜切段', '香菇炒香', '加入青菜翻炒'], tags: ['素菜', '健康'], taste: 'light', suitableFor: ['all'], contraindications: [] },
  { name: '红烧茄子', description: '软糯入味的红烧茄子', category: '素菜', difficulty: 'easy', cookingTime: 20, servings: 2, ingredients: [{ name: '茄子', amount: 300, unit: 'g' }, { name: '酱油', amount: 25, unit: 'ml' }, { name: '糖', amount: 10, unit: 'g' }], steps: ['茄子切块', '煎至金黄', '加酱油糖焖煮'], tags: ['素菜', '家常'], taste: 'savory', suitableFor: ['all'], contraindications: [] },
  { name: '凉拌黄瓜', description: '清爽开胃的凉拌黄瓜', category: '素菜', difficulty: 'easy', cookingTime: 10, servings: 2, ingredients: [{ name: '黄瓜', amount: 300, unit: 'g' }, { name: '蒜', amount: 10, unit: 'g' }, { name: '醋', amount: 20, unit: 'ml' }], steps: ['黄瓜拍碎切块', '蒜末加调料调汁', '拌匀'], tags: ['素菜', '凉菜'], taste: 'spicy', suitableFor: ['all'], contraindications: [] },
  { name: '凉拌木耳', description: '营养丰富的凉拌木耳', category: '素菜', difficulty: 'easy', cookingTime: 15, servings: 2, ingredients: [{ name: '黑木耳', amount: 100, unit: 'g' }, { name: '黄瓜', amount: 100, unit: 'g' }, { name: '蒜', amount: 10, unit: 'g' }], steps: ['木耳泡发焯水', '黄瓜切丝', '加调料拌匀'], tags: ['素菜', '凉菜'], taste: 'spicy', suitableFor: ['all'], contraindications: [] },

  // ========== 更多水产 ==========
  { name: '清蒸鲈鱼', description: '鲜嫩可口的清蒸鲈鱼', category: '水产', difficulty: 'medium', cookingTime: 25, servings: 2, ingredients: [{ name: '鲈鱼', amount: 500, unit: 'g' }, { name: '姜', amount: 15, unit: 'g' }, { name: '葱', amount: 15, unit: 'g' }, { name: '蒸鱼豉油', amount: 30, unit: 'ml' }], steps: ['鱼处理干净划刀', '姜葱放入', '蒸10分钟', '浇豉油热油'], tags: ['水产', '清蒸'], taste: 'light', suitableFor: ['all'], contraindications: [] },
  { name: '红烧带鱼', description: '家常红烧带鱼', category: '水产', difficulty: 'medium', cookingTime: 30, servings: 2, ingredients: [{ name: '带鱼', amount: 300, unit: 'g' }, { name: '酱油', amount: 25, unit: 'ml' }, { name: '糖', amount: 10, unit: 'g' }], steps: ['带鱼切段腌制', '煎至两面金黄', '加酱油糖', '焖煮收汁'], tags: ['水产', '红烧'], taste: 'savory', suitableFor: ['all'], contraindications: [] },
  { name: '香辣虾', description: '麻辣鲜香的香辣虾', category: '水产', difficulty: 'easy', cookingTime: 15, servings: 2, ingredients: [{ name: '虾', amount: 300, unit: 'g' }, { name: '干辣椒', amount: 30, unit: 'g' }, { name: '花椒', amount: 5, unit: 'g' }], steps: ['虾去虾线', '干辣椒花椒蒜爆香', '加入虾翻炒'], tags: ['水产', '川菜'], taste: 'spicy', suitableFor: ['all'], contraindications: [] },
  { name: '白灼虾', description: '原汁原味的白灼虾', category: '水产', difficulty: 'easy', cookingTime: 10, servings: 2, ingredients: [{ name: '活虾', amount: 400, unit: 'g' }, { name: '姜', amount: 20, unit: 'g' }, { name: '料酒', amount: 20, unit: 'ml' }], steps: ['虾洗净', '姜葱料酒煮水', '放入虾变红捞出'], tags: ['水产', '粤菜'], taste: 'light', suitableFor: ['all'], contraindications: [] },
  { name: '油焖大虾', description: '色泽红亮的油焖大虾', category: '水产', difficulty: 'medium', cookingTime: 20, servings: 2, ingredients: [{ name: '大虾', amount: 400, unit: 'g' }, { name: '番茄酱', amount: 30, unit: 'g' }, { name: '糖', amount: 20, unit: 'g' }], steps: ['虾去虾线', '煎至变色', '加番茄酱糖', '焖5分钟'], tags: ['水产', '鲁菜'], taste: 'sweet', suitableFor: ['all'], contraindications: [] },
  { name: '蒜蓉粉丝蒸虾', description: '鲜美多汁的蒜蓉蒸虾', category: '水产', difficulty: 'medium', cookingTime: 20, servings: 2, ingredients: [{ name: '虾', amount: 300, unit: 'g' }, { name: '粉丝', amount: 50, unit: 'g' }, { name: '蒜', amount: 30, unit: 'g' }], steps: ['粉丝泡软铺盘底', '虾摆放', '蒜蓉铺在虾上', '蒸8分钟'], tags: ['水产', '蒸菜'], taste: 'savory', suitableFor: ['all'], contraindications: [] },
  { name: '红烧鲫鱼', description: '家常红烧鲫鱼', category: '水产', difficulty: 'medium', cookingTime: 30, servings: 2, ingredients: [{ name: '鲫鱼', amount: 400, unit: 'g' }, { name: '酱油', amount: 30, unit: 'ml' }, { name: '糖', amount: 10, unit: 'g' }], steps: ['鱼处理干净', '煎至两面金黄', '加酱油糖', '加水焖15分钟'], tags: ['水产', '红烧'], taste: 'savory', suitableFor: ['all'], contraindications: [] },
  { name: '剁椒鱼头', description: '湖南经典剁椒鱼头', category: '水产', difficulty: 'medium', cookingTime: 25, servings: 3, ingredients: [{ name: '鱼头', amount: 600, unit: 'g' }, { name: '剁椒', amount: 80, unit: 'g' }, { name: '姜', amount: 15, unit: 'g' }], steps: ['鱼头洗净劈开', '剁椒姜铺在鱼头上', '蒸15分钟'], tags: ['水产', '湘菜'], taste: 'spicy', suitableFor: ['all'], contraindications: [] },
  { name: '酸菜鱼', description: '酸辣可口的酸菜鱼', category: '水产', difficulty: 'medium', cookingTime: 35, servings: 3, ingredients: [{ name: '草鱼', amount: 600, unit: 'g' }, { name: '酸菜', amount: 200, unit: 'g' }, { name: '泡椒', amount: 30, unit: 'g' }], steps: ['鱼切片上浆', '酸菜炒香', '加水煮酸菜', '放入鱼片'], tags: ['水产', '川菜'], taste: 'spicy', suitableFor: ['all'], contraindications: [] },
  { name: '水煮鱼', description: '麻辣鲜烫的水煮鱼', category: '水产', difficulty: 'hard', cookingTime: 45, servings: 4, ingredients: [{ name: '草鱼', amount: 800, unit: 'g' }, { name: '豆芽', amount: 300, unit: 'g' }, { name: '干辣椒', amount: 50, unit: 'g' }, { name: '花椒', amount: 10, unit: 'g' }], steps: ['鱼切片上浆', '豆芽垫底', '炒香调料加水', '放入鱼片', '浇热油'], tags: ['水产', '川菜'], taste: 'spicy', suitableFor: ['all'], contraindications: [] },
  { name: '松鼠桂鱼', description: '苏州经典名菜', category: '水产', difficulty: 'hard', cookingTime: 50, servings: 3, ingredients: [{ name: '桂鱼', amount: 600, unit: 'g' }, { name: '番茄酱', amount: 80, unit: 'g' }, { name: '糖', amount: 50, unit: 'g' }], steps: ['鱼切花刀', '裹淀粉炸至金黄酥脆', '调番茄酱汁', '浇在鱼上'], tags: ['水产', '苏菜'], taste: 'sweet', suitableFor: ['all'], contraindications: [] },

  // ========== 更多汤类 ==========
  { name: '玉米排骨汤', description: '清甜营养的玉米排骨汤', category: '汤', difficulty: 'easy', cookingTime: 90, servings: 4, ingredients: [{ name: '排骨', amount: 400, unit: 'g' }, { name: '玉米', amount: 200, unit: 'g' }, { name: '胡萝卜', amount: 100, unit: 'g' }], steps: ['排骨焯水', '玉米胡萝卜切块', '放入锅中煮90分钟'], tags: ['汤', '养生'], taste: 'light', suitableFor: ['all'], contraindications: [] },
  { name: '莲藕排骨汤', description: '润燥滋补的莲藕排骨汤', category: '汤', difficulty: 'easy', cookingTime: 120, servings: 4, ingredients: [{ name: '排骨', amount: 400, unit: 'g' }, { name: '莲藕', amount: 300, unit: 'g' }], steps: ['排骨焯水', '莲藕切块', '小火煮2小时'], tags: ['汤', '养生'], taste: 'light', suitableFor: ['all'], contraindications: [] },
  { name: '冬瓜排骨汤', description: '清淡解暑的冬瓜排骨汤', category: '汤', difficulty: 'easy', cookingTime: 60, servings: 4, ingredients: [{ name: '排骨', amount: 400, unit: 'g' }, { name: '冬瓜', amount: 400, unit: 'g' }], steps: ['排骨焯水', '冬瓜切块', '煮1小时'], tags: ['汤', '清淡'], taste: 'light', suitableFor: ['all'], contraindications: [] },
  { name: '番茄蛋花汤', description: '家常快手汤品', category: '汤', difficulty: 'easy', cookingTime: 15, servings: 2, ingredients: [{ name: '番茄', amount: 200, unit: 'g' }, { name: '鸡蛋', amount: 2, unit: '个' }], steps: ['番茄切块', '加水煮番茄', '倒入蛋液', '调味撒葱花'], tags: ['汤', '快手'], taste: 'light', suitableFor: ['all'], contraindications: [] },
  { name: '紫菜蛋花汤', description: '简单营养的紫菜汤', category: '汤', difficulty: 'easy', cookingTime: 10, servings: 2, ingredients: [{ name: '紫菜', amount: 10, unit: 'g' }, { name: '鸡蛋', amount: 2, unit: '个' }, { name: '虾皮', amount: 10, unit: 'g' }], steps: ['紫菜撕成小片', '加水煮沸', '加入虾皮', '倒入蛋液'], tags: ['汤', '快手'], taste: 'light', suitableFor: ['all'], contraindications: [] },
  { name: '酸辣汤', description: '开胃的酸辣汤', category: '汤', difficulty: 'easy', cookingTime: 20, servings: 2, ingredients: [{ name: '豆腐', amount: 100, unit: 'g' }, { name: '木耳', amount: 30, unit: 'g' }, { name: '鸡蛋', amount: 1, unit: '个' }, { name: '醋', amount: 30, unit: 'ml' }], steps: ['食材切丝', '加水煮沸', '放入食材', '勾芡倒蛋液', '加醋'], tags: ['汤', '川菜'], taste: 'spicy', suitableFor: ['all'], contraindications: [] },
  { name: '疙瘩汤', description: '北方家常汤饭', category: '汤', difficulty: 'easy', cookingTime: 25, servings: 2, ingredients: [{ name: '面粉', amount: 100, unit: 'g' }, { name: '番茄', amount: 100, unit: 'g' }, { name: '鸡蛋', amount: 1, unit: '个' }], steps: ['面粉加水搅成小疙瘩', '番茄炒香加水', '放入疙瘩煮熟'], tags: ['汤', '家常'], taste: 'light', suitableFor: ['all'], contraindications: [] },
  { name: '菌菇汤', description: '鲜香的菌菇汤', category: '汤', difficulty: 'easy', cookingTime: 30, servings: 3, ingredients: [{ name: '香菇', amount: 100, unit: 'g' }, { name: '金针菇', amount: 100, unit: 'g' }, { name: '白玉菇', amount: 100, unit: 'g' }], steps: ['菌菇洗净', '加水煮沸', '小火煮20分钟'], tags: ['汤', '养生'], taste: 'light', suitableFor: ['all'], contraindications: [] },
  { name: '萝卜排骨汤', description: '冬季暖身汤品', category: '汤', difficulty: 'easy', cookingTime: 90, servings: 4, ingredients: [{ name: '排骨', amount: 400, unit: 'g' }, { name: '白萝卜', amount: 400, unit: 'g' }], steps: ['排骨焯水', '萝卜切块', '煮90分钟'], tags: ['汤', '冬季'], taste: 'light', suitableFor: ['all'], contraindications: [] },
  { name: '海带排骨汤', description: '营养丰富的海带汤', category: '汤', difficulty: 'easy', cookingTime: 90, servings: 4, ingredients: [{ name: '排骨', amount: 400, unit: 'g' }, { name: '海带', amount: 200, unit: 'g' }], steps: ['排骨焯水', '海带泡发洗净', '煮90分钟'], tags: ['汤', '营养'], taste: 'light', suitableFor: ['all'], contraindications: [] },

  // ========== 更多主食 ==========
  { name: '扬州炒饭', description: '配料丰富的扬州炒饭', category: '主食', difficulty: 'medium', cookingTime: 20, servings: 2, ingredients: [{ name: '米饭', amount: 400, unit: 'g' }, { name: '鸡蛋', amount: 2, unit: '个' }, { name: '火腿', amount: 50, unit: 'g' }, { name: '虾仁', amount: 50, unit: 'g' }, { name: '青豆', amount: 30, unit: 'g' }], steps: ['配料切丁', '鸡蛋炒熟盛出', '配料炒匀', '加入米饭鸡蛋', '翻炒出锅'], tags: ['主食', '苏菜'], taste: 'savory', suitableFor: ['all'], contraindications: [] },
  { name: '葱油拌面', description: '上海经典本帮面', category: '主食', difficulty: 'easy', cookingTime: 20, servings: 1, ingredients: [{ name: '面条', amount: 150, unit: 'g' }, { name: '小葱', amount: 100, unit: 'g' }, { name: '酱油', amount: 30, unit: 'ml' }, { name: '糖', amount: 10, unit: 'g' }], steps: ['小葱切段炸焦', '酱油糖调汁', '面条煮熟', '拌匀食用'], tags: ['主食', '本帮'], taste: 'savory', suitableFor: ['all'], contraindications: [] },
  { name: '热干面', description: '武汉经典早餐', category: '主食', difficulty: 'medium', cookingTime: 20, servings: 1, ingredients: [{ name: '碱水面', amount: 150, unit: 'g' }, { name: '芝麻酱', amount: 30, unit: 'g' }, { name: '萝卜丁', amount: 30, unit: 'g' }], steps: ['面条煮至断生', '芝麻酱酱油调开', '面条沥水', '加入调料拌匀'], tags: ['主食', '武汉'], taste: 'savory', suitableFor: ['all'], contraindications: [] },
  { name: '重庆小面', description: '麻辣鲜香的重庆小面', category: '主食', difficulty: 'medium', cookingTime: 20, servings: 1, ingredients: [{ name: '面条', amount: 150, unit: 'g' }, { name: '辣椒油', amount: 30, unit: 'ml' }, { name: '花椒粉', amount: 3, unit: 'g' }, { name: '青菜', amount: 50, unit: 'g' }], steps: ['调制麻辣汤底', '煮面条和青菜', '放入碗中', '浇上汤底'], tags: ['主食', '川菜'], taste: 'spicy', suitableFor: ['all'], contraindications: [] },
  { name: '担担面', description: '四川传统担担面', category: '主食', difficulty: 'medium', cookingTime: 25, servings: 1, ingredients: [{ name: '面条', amount: 150, unit: 'g' }, { name: '肉末', amount: 50, unit: 'g' }, { name: '花生碎', amount: 20, unit: 'g' }, { name: '芝麻酱', amount: 20, unit: 'g' }], steps: ['肉末炒香', '芝麻酱酱油调汁', '煮面条', '放入碗中加肉末花生碎'], tags: ['主食', '川菜'], taste: 'spicy', suitableFor: ['all'], contraindications: [] },
  { name: '炸酱面', description: '老北京炸酱面', category: '主食', difficulty: 'medium', cookingTime: 30, servings: 2, ingredients: [{ name: '面条', amount: 300, unit: 'g' }, { name: '五花肉', amount: 200, unit: 'g' }, { name: '黄酱', amount: 80, unit: 'g' }, { name: '黄瓜', amount: 100, unit: 'g' }], steps: ['肉切小丁', '炸酱炒肉丁', '加酱炒浓', '煮面条', '配菜切丝'], tags: ['主食', '京菜'], taste: 'savory', suitableFor: ['all'], contraindications: [] },
  { name: '刀削面', description: '山西经典面食', category: '主食', difficulty: 'hard', cookingTime: 30, servings: 2, ingredients: [{ name: '面粉', amount: 300, unit: 'g' }, { name: '五花肉', amount: 150, unit: 'g' }, { name: '番茄', amount: 100, unit: 'g' }, { name: '青菜', amount: 100, unit: 'g' }], steps: ['和面醒发', '削成面条', '炒浇头', '煮面条'], tags: ['主食', '晋菜'], taste: 'savory', suitableFor: ['all'], contraindications: [] },
  { name: 'biangbiang面', description: '陕西特色宽面', category: '主食', difficulty: 'medium', cookingTime: 30, servings: 1, ingredients: [{ name: '面粉', amount: 200, unit: 'g' }, { name: '辣椒油', amount: 30, unit: 'ml' }, { name: '酱油', amount: 15, unit: 'ml' }, { name: '蒜', amount: 10, unit: 'g' }], steps: ['和面擀成宽条', '煮熟', '加入调料拌匀', '浇热油'], tags: ['主食', '陕菜'], taste: 'savory', suitableFor: ['all'], contraindications: [] },
  { name: '饸饹面', description: '西北荞麦面', category: '主食', difficulty: 'medium', cookingTime: 30, servings: 2, ingredients: [{ name: '荞麦面', amount: 300, unit: 'g' }, { name: '羊肉', amount: 150, unit: 'g' }, { name: '萝卜', amount: 100, unit: 'g' }], steps: ['和面', '羊肉萝卜炒浇头', '压面煮熟', '拌匀'], tags: ['主食', '西北'], taste: 'savory', suitableFor: ['all'], contraindications: [] },
  { name: '盖浇饭', description: '快捷美味的盖浇饭', category: '主食', difficulty: 'easy', cookingTime: 20, servings: 1, ingredients: [{ name: '米饭', amount: 300, unit: 'g' }, { name: '茄子', amount: 150, unit: 'g' }, { name: '肉末', amount: 80, unit: 'g' }, { name: '豆瓣酱', amount: 20, unit: 'g' }], steps: ['茄子切丁', '肉末炒散', '加茄子和豆瓣酱', '炒熟浇在米饭上'], tags: ['主食', '快手'], taste: 'savory', suitableFor: ['all'], contraindications: [] },
  { name: '石锅拌饭', description: '韩式石锅拌饭', category: '主食', difficulty: 'medium', cookingTime: 30, servings: 1, ingredients: [{ name: '米饭', amount: 300, unit: 'g' }, { name: '牛肉', amount: 80, unit: 'g' }, { name: '鸡蛋', amount: 1, unit: '个' }, { name: '菠菜', amount: 30, unit: 'g' }, { name: '胡萝卜', amount: 30, unit: 'g' }], steps: ['石锅刷油铺米饭', '上面铺蔬菜和肉', '煎个荷包蛋放上面', '配辣酱拌匀'], tags: ['主食', '韩式'], taste: 'savory', suitableFor: ['all'], contraindications: [] },

  // ========== 更多凉菜 ==========
  { name: '凉拌海带丝', description: '爽脆的凉拌海带', category: '凉菜', difficulty: 'easy', cookingTime: 15, servings: 2, ingredients: [{ name: '海带', amount: 200, unit: 'g' }, { name: '蒜', amount: 10, unit: 'g' }, { name: '醋', amount: 20, unit: 'ml' }, { name: '辣椒油', amount: 15, unit: 'ml' }], steps: ['海带泡发切丝焯水', '蒜末调料调汁', '拌匀'], tags: ['凉菜', '开胃'], taste: 'spicy', suitableFor: ['all'], contraindications: [] },
  { name: '凉拌猪耳朵', description: 'Q弹爽脆的凉拌猪耳', category: '凉菜', difficulty: 'medium', cookingTime: 60, servings: 3, ingredients: [{ name: '猪耳朵', amount: 300, unit: 'g' }, { name: '黄瓜', amount: 100, unit: 'g' }, { name: '蒜', amount: 15, unit: 'g' }, { name: '辣椒油', amount: 20, unit: 'ml' }], steps: ['猪耳朵煮熟', '晾凉切丝', '黄瓜切丝', '加调料拌匀'], tags: ['凉菜', '下酒'], taste: 'spicy', suitableFor: ['all'], contraindications: [] },
  { name: '凉拌金针菇', description: '爽滑的凉拌金针菇', category: '凉菜', difficulty: 'easy', cookingTime: 10, servings: 2, ingredients: [{ name: '金针菇', amount: 200, unit: 'g' }, { name: '黄瓜', amount: 100, unit: 'g' }, { name: '蒜', amount: 10, unit: 'g' }], steps: ['金针菇焯水过凉', '黄瓜切丝', '加调料拌匀'], tags: ['凉菜', '爽滑'], taste: 'spicy', suitableFor: ['all'], contraindications: [] },
  { name: '凉拌腐竹', description: '豆香浓郁的凉拌腐竹', category: '凉菜', difficulty: 'easy', cookingTime: 15, servings: 2, ingredients: [{ name: '腐竹', amount: 150, unit: 'g' }, { name: '黄瓜', amount: 100, unit: 'g' }, { name: '木耳', amount: 50, unit: 'g' }], steps: ['腐竹木耳泡发焯水', '黄瓜切块', '加调料拌匀'], tags: ['凉菜', '豆香'], taste: 'spicy', suitableFor: ['all'], contraindications: [] },
  { name: '凉拌牛肉', description: '香辣入味的凉拌牛肉', category: '凉菜', difficulty: 'medium', cookingTime: 90, servings: 3, ingredients: [{ name: '牛腱子肉', amount: 500, unit: 'g' }, { name: '香菜', amount: 50, unit: 'g' }, { name: '蒜', amount: 15, unit: 'g' }, { name: '辣椒油', amount: 30, unit: 'ml' }], steps: ['牛肉煮熟放凉', '切片', '加香菜蒜末调料', '拌匀'], tags: ['凉菜', '下酒'], taste: 'spicy', suitableFor: ['all'], contraindications: [] },
  { name: '皮蛋豆腐', description: '经典的皮蛋豆腐', category: '凉菜', difficulty: 'easy', cookingTime: 10, servings: 2, ingredients: [{ name: '皮蛋', amount: 2, unit: '个' }, { name: '内酯豆腐', amount: 300, unit: 'g' }, { name: '蒜', amount: 10, unit: 'g' }, { name: '酱油', amount: 20, unit: 'ml' }], steps: ['豆腐摆盘', '皮蛋切块放在豆腐上', '撒蒜末', '浇酱油'], tags: ['凉菜', '经典'], taste: 'savory', suitableFor: ['all'], contraindications: [] },
  { name: '凉拌鸡丝', description: '低脂健康的凉拌鸡丝', category: '凉菜', difficulty: 'medium', cookingTime: 40, servings: 2, ingredients: [{ name: '鸡胸肉', amount: 300, unit: 'g' }, { name: '黄瓜', amount: 100, unit: 'g' }, { name: '胡萝卜', amount: 50, unit: 'g' }, { name: '蒜', amount: 10, unit: 'g' }], steps: ['鸡胸肉煮熟放凉', '手撕成丝', '黄瓜胡萝卜切丝', '加调料拌匀'], tags: ['凉菜', '低脂'], taste: 'spicy', suitableFor: ['all'], contraindications: [] },

  // ========== 更多甜品 ==========
  { name: '红糖糍粑', description: '软糯香甜的红糖糍粑', category: '甜品', difficulty: 'medium', cookingTime: 30, servings: 2, ingredients: [{ name: '糯米', amount: 200, unit: 'g' }, { name: '红糖', amount: 50, unit: 'g' }, { name: '黄豆粉', amount: 30, unit: 'g' }], steps: ['糯米蒸熟', '捣成糍粑', '切块油炸', '裹黄豆粉', '淋红糖'], tags: ['甜品', '软糯'], taste: 'sweet', suitableFor: ['all'], contraindications: ['diabetes'] },
  { name: '南瓜饼', description: '外酥里糯的南瓜饼', category: '甜品', difficulty: 'easy', cookingTime: 30, servings: 3, ingredients: [{ name: '南瓜', amount: 300, unit: 'g' }, { name: '糯米粉', amount: 200, unit: 'g' }, { name: '糖', amount: 30, unit: 'g' }, { name: '豆沙', amount: 100, unit: 'g' }], steps: ['南瓜蒸熟捣泥', '加糯米粉和糖和面', '包豆沙', '煎至两面金黄'], tags: ['甜品', '家常'], taste: 'sweet', suitableFor: ['all'], contraindications: ['diabetes'] },
  { name: '紫薯饼', description: '营养丰富的紫薯饼', category: '甜品', difficulty: 'easy', cookingTime: 30, servings: 2, ingredients: [{ name: '紫薯', amount: 300, unit: 'g' }, { name: '糯米粉', amount: 150, unit: 'g' }, { name: '糖', amount: 30, unit: 'g' }, { name: '牛奶', amount: 50, unit: 'ml' }], steps: ['紫薯蒸熟', '加糯米粉糖牛奶和面', '煎至金黄'], tags: ['甜品', '营养'], taste: 'sweet', suitableFor: ['all'], contraindications: ['diabetes'] },
  { name: '麻薯', description: 'Q弹的日式麻薯', category: '甜品', difficulty: 'medium', cookingTime: 30, servings: 3, ingredients: [{ name: '糯米粉', amount: 200, unit: 'g' }, { name: '牛奶', amount: 200, unit: 'ml' }, { name: '糖', amount: 40, unit: 'g' }, { name: '玉米淀粉', amount: 50, unit: 'g' }], steps: ['所有材料搅匀', '蒸20分钟', '取出晾凉', '揉至光滑', '裹熟粉'], tags: ['甜品', 'Q弹'], taste: 'sweet', suitableFor: ['all'], contraindications: ['diabetes'] },
  { name: '芝士焗红薯', description: '香浓的芝士焗红薯', category: '甜品', difficulty: 'easy', cookingTime: 30, servings: 2, ingredients: [{ name: '红薯', amount: 400, unit: 'g' }, { name: '芝士', amount: 100, unit: 'g' }, { name: '牛奶', amount: 50, unit: 'ml' }, { name: '糖', amount: 20, unit: 'g' }], steps: ['红薯蒸熟', '加牛奶糖捣成泥', '铺上芝士', '烤箱烤至金黄'], tags: ['甜品', '香浓'], taste: 'sweet', suitableFor: ['all'], contraindications: ['diabetes', 'lactose_intolerant'] },
  { name: '杨枝甘露', description: '经典港式甜品', category: '甜品', difficulty: 'medium', cookingTime: 40, servings: 2, ingredients: [{ name: '芒果', amount: 200, unit: 'g' }, { name: '西米', amount: 50, unit: 'g' }, { name: '椰浆', amount: 100, unit: 'ml' }, { name: '西柚', amount: 50, unit: 'g' }, { name: '糖', amount: 30, unit: 'g' }], steps: ['西米煮熟过凉', '芒果切丁', '椰浆糖调匀', '放入西米芒果西柚'], tags: ['甜品', '港式'], taste: 'sweet', suitableFor: ['all'], contraindications: ['diabetes'] },
  { name: '双皮奶', description: '广式经典甜品', category: '甜品', difficulty: 'medium', cookingTime: 30, servings: 2, ingredients: [{ name: '牛奶', amount: 300, unit: 'ml' }, { name: '蛋清', amount: 2, unit: '个' }, { name: '糖', amount: 30, unit: 'g' }], steps: ['牛奶加热', '蛋清糖打散', '混合均匀', '蒸15分钟'], tags: ['甜品', '粤菜'], taste: 'sweet', suitableFor: ['all'], contraindications: ['diabetes', 'lactose_intolerant'] },
  { name: '炸鲜奶', description: '外脆内嫩的炸鲜奶', category: '甜品', difficulty: 'medium', cookingTime: 40, servings: 2, ingredients: [{ name: '牛奶', amount: 300, unit: 'ml' }, { name: '淀粉', amount: 80, unit: 'g' }, { name: '面包糠', amount: 100, unit: 'g' }, { name: '糖', amount: 30, unit: 'g' }], steps: ['牛奶淀粉糖煮浓', '冷藏凝固', '切条裹淀粉蛋液面包糠', '油炸金黄'], tags: ['甜品', '外脆'], taste: 'sweet', suitableFor: ['all'], contraindications: ['diabetes', 'lactose_intolerant'] },
  { name: '龟苓膏', description: '清热降火的传统甜品', category: '甜品', difficulty: 'easy', cookingTime: 20, servings: 1, ingredients: [{ name: '龟苓膏粉', amount: 30, unit: 'g' }, { name: '水', amount: 500, unit: 'ml' }, { name: '蜂蜜', amount: 20, unit: 'g' }, { name: '水果', amount: 50, unit: 'g' }], steps: ['龟苓膏粉加水搅匀', '煮沸倒入模具', '凝固后切块', '加蜂蜜水果食用'], tags: ['甜品', '清热'], taste: 'light', suitableFor: ['all'], contraindications: [] },
  { name: '糯米藕', description: '香甜软糯的糯米藕', category: '甜品', difficulty: 'medium', cookingTime: 90, servings: 3, ingredients: [{ name: '莲藕', amount: 400, unit: 'g' }, { name: '糯米', amount: 150, unit: 'g' }, { name: '红糖', amount: 80, unit: 'g' }, { name: '冰糖', amount: 30, unit: 'g' }], steps: ['糯米泡发', '藕去皮切段', '糯米塞入藕孔', '加红糖冰糖煮90分钟'], tags: ['甜品', '软糯'], taste: 'sweet', suitableFor: ['all'], contraindications: ['diabetes'] },
];

// ==================== Recipe Database Class ====================

export class RecipeDatabase {
  private recipes: Map<string, Recipe> = new Map();

  constructor() {
    this.initialize();
  }

  private initialize() {
    for (const raw of RECIPE_DATABASE) {
      const recipe: Recipe = {
        id: `howtocook-${raw.name}`,
        name: raw.name,
        description: raw.description,
        category: raw.category,
        difficulty: raw.difficulty,
        cookingTime: raw.cookingTime,
        servings: raw.servings,
        ingredients: raw.ingredients,
        steps: raw.steps.map((desc, i) => ({ step: i + 1, description: desc })),
        nutrition: calculateNutrition(raw.ingredients),
        tags: raw.tags,
        taste: raw.taste,
        suitableFor: raw.suitableFor as any,
        contraindications: raw.contraindications as any,
        source: 'howtocook',
        createdAt: new Date(),
      };
      this.recipes.set(recipe.id, recipe);
    }
    console.log(`[RecipeDatabase] Initialized ${this.recipes.size} recipes`);
  }

  async searchRecipes(params: {
    query?: string;
    category?: string;
    difficulty?: string;
    tags?: string[];
    taste?: string;
  }): Promise<{ recipes: Recipe[]; total: number }> {
    let results: Recipe[] = Array.from(this.recipes.values());

    if (params.query) {
      const lower = params.query.toLowerCase();
      results = results.filter(r =>
        r.name.toLowerCase().includes(lower) ||
        r.description.toLowerCase().includes(lower) ||
        r.tags.some(t => t.toLowerCase().includes(lower))
      );
    }

    if (params.category) {
      results = results.filter(r => r.category === params.category);
    }

    if (params.difficulty) {
      results = results.filter(r => r.difficulty === params.difficulty);
    }

    if (params.tags && params.tags.length > 0) {
      results = results.filter(r =>
        params.tags!.some(tag => r.tags.includes(tag))
      );
    }

    if (params.taste) {
      results = results.filter(r => r.taste === params.taste);
    }

    return { recipes: results, total: results.length };
  }

  async getRecipeById(id: string): Promise<Recipe | null> {
    return this.recipes.get(id) || null;
  }

  async getRandomRecipes(count: number = 3): Promise<Recipe[]> {
    const recipes = Array.from(this.recipes.values());
    const shuffled = recipes.sort(() => Math.random() - 0.5);
    return shuffled.slice(0, count);
  }

  async getCategories(): Promise<string[]> {
    const categories = new Set<string>();
    for (const recipe of this.recipes.values()) {
      categories.add(recipe.category);
    }
    return Array.from(categories);
  }

  async getAllTags(): Promise<string[]> {
    const tags = new Set<string>();
    for (const recipe of this.recipes.values()) {
      for (const tag of recipe.tags) {
        tags.add(tag);
      }
    }
    return Array.from(tags);
  }

  async getByContraindication(healthCondition: string): Promise<Recipe[]> {
    return Array.from(this.recipes.values()).filter(
      r => !r.contraindications.includes(healthCondition as any)
    );
  }

  async getSuitableFor(healthConditions: string[]): Promise<Recipe[]> {
    return Array.from(this.recipes.values()).filter(r =>
      healthConditions.every(
        condition => r.suitableFor.includes('all') || r.suitableFor.includes(condition as any)
      )
    );
  }

  getSize(): number {
    return this.recipes.size;
  }
}

export const recipeDatabase = new RecipeDatabase();
